# coding: utf-8

"""
    Communication

    Communication API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from communication_client.models.incoming_banking_transaction_format_type import IncomingBankingTransactionFormatType

class TestIncomingBankingTransactionFormatType(unittest.TestCase):
    """IncomingBankingTransactionFormatType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncomingBankingTransactionFormatType(self):
        """Test IncomingBankingTransactionFormatType"""
        # inst = IncomingBankingTransactionFormatType()

if __name__ == '__main__':
    unittest.main()
