# coding: utf-8

"""
    Communication

    Communication API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from communication_client.models.subject_reference_parameters_dto_billing_relation_subject_reference_parameters_dto import SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO

class TestSubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO(unittest.TestCase):
    """SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO:
        """Test SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO`
        """
        model = SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO()
        if include_optional:
            return SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO(
                type = 'BillingRelation',
                contract_number = ''
            )
        else:
            return SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO(
        )
        """

    def testSubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO(self):
        """Test SubjectReferenceParametersDTOBillingRelationSubjectReferenceParametersDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
