# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MoveRequestStatus(str, Enum):
    """
    MoveRequestStatus
    """

    """
    allowed enum values
    """
    NEW = 'new'
    PENDINGATCUSTOMER = 'pendingatcustomer'
    PENDINGATSUPPLIER = 'pendingatsupplier'
    PROCESSED = 'processed'
    REJECTED = 'rejected'
    GATHERINGDATA = 'gatheringdata'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MoveRequestStatus from a JSON string"""
        return cls(json.loads(json_str))


