version: 2

multi-ecosystem-groups:
  all-updates:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "deps"
      include: "scope"
    target-branch: "main"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "all-updates"
    patterns:
      - "*"

  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "all-updates"
    patterns:
      - "*"
