repos:
  - repo: local
    hooks:
      - id: prevent-manual-requirements-edits
        name: Prevent manual changes to requirements.txt
        entry: scripts/hooks/check-requirements.sh
        language: script
        types: [text]

      - id: nbstripout-autoadd
        name: nbstripout (auto-add notebooks)
        entry: scripts/hooks/nbstripout-autoadd.sh
        language: script
        types: [jupyter]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.7
    hooks:
      - id: jupytext
        args: [--sync]
        require_serial: true
