# coding: utf-8

"""
    Metering

    MeterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metering_client.models.aggregated_service_consumption_per_period_request import AggregatedServiceConsumptionPerPeriodRequest

class TestAggregatedServiceConsumptionPerPeriodRequest(unittest.TestCase):
    """AggregatedServiceConsumptionPerPeriodRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AggregatedServiceConsumptionPerPeriodRequest:
        """Test AggregatedServiceConsumptionPerPeriodRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AggregatedServiceConsumptionPerPeriodRequest`
        """
        model = AggregatedServiceConsumptionPerPeriodRequest()
        if include_optional:
            return AggregatedServiceConsumptionPerPeriodRequest(
                service_location_ids = [
                    ''
                    ],
                group_by_period = 'none'
            )
        else:
            return AggregatedServiceConsumptionPerPeriodRequest(
        )
        """

    def testAggregatedServiceConsumptionPerPeriodRequest(self):
        """Test AggregatedServiceConsumptionPerPeriodRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
