# coding: utf-8

"""
    Metering

    MeterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metering_client.models.property_group_metering_configuration_dto_api_response_dto import PropertyGroupMeteringConfigurationDTOApiResponseDTO

class TestPropertyGroupMeteringConfigurationDTOApiResponseDTO(unittest.TestCase):
    """PropertyGroupMeteringConfigurationDTOApiResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertyGroupMeteringConfigurationDTOApiResponseDTO:
        """Test PropertyGroupMeteringConfigurationDTOApiResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PropertyGroupMeteringConfigurationDTOApiResponseDTO`
        """
        model = PropertyGroupMeteringConfigurationDTOApiResponseDTO()
        if include_optional:
            return PropertyGroupMeteringConfigurationDTOApiResponseDTO(
                errors = [
                    metering_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = null, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            metering_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = null, 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True,
                data = metering_client.models.property_group_metering_configuration_dto.PropertyGroupMeteringConfigurationDTO(
                    id = '', 
                    entity_type = null, 
                    created_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    discriminator = '', 
                    _etag = '', 
                    require_attention = True, 
                    has_errors = True, 
                    has_warnings = True, 
                    is_read_only = True, 
                    organisation_id = '', 
                    property_group = null, 
                    output_channels = [
                        metering_client.models.output_channel_dto.OutputChannelDTO(
                            id = '', 
                            name = '', 
                            formula = null, 
                            unit_of_measure = null, 
                            metering_type = null, 
                            utility_type = null, 
                            validation_result = null, )
                        ], 
                    validated = True, )
            )
        else:
            return PropertyGroupMeteringConfigurationDTOApiResponseDTO(
        )
        """

    def testPropertyGroupMeteringConfigurationDTOApiResponseDTO(self):
        """Test PropertyGroupMeteringConfigurationDTOApiResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
