# coding: utf-8

"""
    Metering

    MeterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metering_client.models.input_missing_reason import InputMissingReason

class TestInputMissingReason(unittest.TestCase):
    """InputMissingReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputMissingReason(self):
        """Test InputMissingReason"""
        # inst = InputMissingReason()

if __name__ == '__main__':
    unittest.main()
