# coding: utf-8

"""
    Metering

    MeterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metering_client.models.consumption_type_dto_list_api_response_dto import ConsumptionTypeDTOListApiResponseDTO

class TestConsumptionTypeDTOListApiResponseDTO(unittest.TestCase):
    """ConsumptionTypeDTOListApiResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsumptionTypeDTOListApiResponseDTO:
        """Test ConsumptionTypeDTOListApiResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConsumptionTypeDTOListApiResponseDTO`
        """
        model = ConsumptionTypeDTOListApiResponseDTO()
        if include_optional:
            return ConsumptionTypeDTOListApiResponseDTO(
                errors = [
                    metering_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = null, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            metering_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = null, 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True,
                data = [
                    metering_client.models.consumption_type_dto.ConsumptionTypeDTO(
                        utility_type = null, 
                        unit_of_measure = null, 
                        time_of_use = '', 
                        formula_stream_name = '', )
                    ]
            )
        else:
            return ConsumptionTypeDTOListApiResponseDTO(
        )
        """

    def testConsumptionTypeDTOListApiResponseDTO(self):
        """Test ConsumptionTypeDTOListApiResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
