# coding: utf-8

"""
    Metering

    MeterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metering_client.models.base_metering_issue_details_dto_uncontracted_consumption_metering_issue_details_dto import BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO

class TestBaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO(unittest.TestCase):
    """BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO:
        """Test BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO`
        """
        model = BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO()
        if include_optional:
            return BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO(
                type = 'BaseMeteringIssueDetailsDTO:UncontractedConsumption',
                total_consumption = 1.337,
                service_location_id = '',
                service_location_address_display = '',
                contract_id = '',
                contract_number = '',
                utility_type = 'none',
                unit_of_measure = 'none',
                evaluation_window_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                evaluation_window_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                evaluation_window_days = 56,
                grace_days_before_supply_start = 56,
                grace_days_after_supply_end = 56
            )
        else:
            return BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO(
        )
        """

    def testBaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO(self):
        """Test BaseMeteringIssueDetailsDTOUncontractedConsumptionMeteringIssueDetailsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
