# coding: utf-8

"""
    Metering

    MeterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metering_client.models.service_consumption_value_dto import ServiceConsumptionValueDTO

class TestServiceConsumptionValueDTO(unittest.TestCase):
    """ServiceConsumptionValueDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceConsumptionValueDTO:
        """Test ServiceConsumptionValueDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceConsumptionValueDTO`
        """
        model = ServiceConsumptionValueDTO()
        if include_optional:
            return ServiceConsumptionValueDTO(
                value = 1.337,
                start_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ServiceConsumptionValueDTO(
        )
        """

    def testServiceConsumptionValueDTO(self):
        """Test ServiceConsumptionValueDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
