# coding: utf-8

"""
    Metering

    MeterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metering_client.models.muting_rule_overview_count_dto import MutingRuleOverviewCountDTO

class TestMutingRuleOverviewCountDTO(unittest.TestCase):
    """MutingRuleOverviewCountDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MutingRuleOverviewCountDTO:
        """Test MutingRuleOverviewCountDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MutingRuleOverviewCountDTO`
        """
        model = MutingRuleOverviewCountDTO()
        if include_optional:
            return MutingRuleOverviewCountDTO(
                active = 56,
                expired = 56
            )
        else:
            return MutingRuleOverviewCountDTO(
        )
        """

    def testMutingRuleOverviewCountDTO(self):
        """Test MutingRuleOverviewCountDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
