# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.paged_response_model_dtoof_outgoing_banking_transaction_dto import PagedResponseModelDTOOfOutgoingBankingTransactionDTO

class TestPagedResponseModelDTOOfOutgoingBankingTransactionDTO(unittest.TestCase):
    """PagedResponseModelDTOOfOutgoingBankingTransactionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PagedResponseModelDTOOfOutgoingBankingTransactionDTO:
        """Test PagedResponseModelDTOOfOutgoingBankingTransactionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PagedResponseModelDTOOfOutgoingBankingTransactionDTO`
        """
        model = PagedResponseModelDTOOfOutgoingBankingTransactionDTO()
        if include_optional:
            return PagedResponseModelDTOOfOutgoingBankingTransactionDTO(
                results = [
                    billing_client.models.outgoing_banking_transaction_dto.OutgoingBankingTransactionDTO(
                        identification = '',
                        sequence_num = 56,
                        type = 'paymentrequests',
                        status = 'created',
                        provider_type = 'twikey',
                        mutation_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        company_bank_account = billing_client.models.outgoing_banking_transaction_company_bank_account_dto.OutgoingBankingTransactionCompanyBankAccountDTO(
                            id = '',
                            iban = '',
                            bic = '',
                            account_holder = '',
                            sepa_creditor_id = '',
                            address = billing_client.models.address_dto.AddressDTO(
                                street_name = '',
                                street_number = '',
                                street_number_addition = '',
                                postal_code = '',
                                building_name = '',
                                locality = '',
                                city = '',
                                country = 'aut',
                                localized_display = '',
                                line_one = '',
                                line_two = '', ), ),
                        file_name = '',
                        internal_file_path = '',
                        total_amount = 1.337,
                        entity_counts = billing_client.models.outgoing_banking_transaction_entity_counts_dto.OutgoingBankingTransactionEntityCountsDTO(
                            number_of_mutations = 56,
                            confirmed_mutations = 56,
                            reversed_mutations = 56, ),
                        migrated = True,
                        locked = True,
                        confirming_incoming_banking_transactions = {
                            'key' : ''
                            },
                        organisation_id = '',
                        id = '',
                        entity_type = 'none',
                        created_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        discriminator = '',
                        _etag = '',
                        has_errors = True,
                        is_read_only = True, )
                    ],
                has_next_page = True,
                next_page_token = '',
                total_records = 56,
                sortable_fields = [
                    ''
                    ],
                aggregate_details = [
                    billing_client.models.aggregate_details_dto.AggregateDetailsDTO(
                        code = '',
                        translation = '',
                        value = 1.337,
                        value_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PagedResponseModelDTOOfOutgoingBankingTransactionDTO(
        )
        """

    def testPagedResponseModelDTOOfOutgoingBankingTransactionDTO(self):
        """Test PagedResponseModelDTOOfOutgoingBankingTransactionDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
