# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.update_outgoing_mutation_entry_request import UpdateOutgoingMutationEntryRequest

class TestUpdateOutgoingMutationEntryRequest(unittest.TestCase):
    """UpdateOutgoingMutationEntryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOutgoingMutationEntryRequest:
        """Test UpdateOutgoingMutationEntryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOutgoingMutationEntryRequest`
        """
        model = UpdateOutgoingMutationEntryRequest()
        if include_optional:
            return UpdateOutgoingMutationEntryRequest(
                amount = 1.337,
                payment_reference = '',
                iban = ''
            )
        else:
            return UpdateOutgoingMutationEntryRequest(
        )
        """

    def testUpdateOutgoingMutationEntryRequest(self):
        """Test UpdateOutgoingMutationEntryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
