# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.bulk_cancel_payment_plan_request import BulkCancelPaymentPlanRequest

class TestBulkCancelPaymentPlanRequest(unittest.TestCase):
    """BulkCancelPaymentPlanRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkCancelPaymentPlanRequest:
        """Test BulkCancelPaymentPlanRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkCancelPaymentPlanRequest`
        """
        model = BulkCancelPaymentPlanRequest()
        if include_optional:
            return BulkCancelPaymentPlanRequest(
                only_validate = True,
                var_query_params = billing_client.models.payment_plan_query_params.PaymentPlanQueryParams(
                    payment_plan_number = '',
                    debtor_id = '',
                    customer_account_number = '',
                    customer_name = '',
                    statuses = [
                        ''
                        ],
                    installment_status = 'pending',
                    start_date_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                    start_date_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                    due_date_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                    due_date_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                    amount_from = 1.337,
                    amount_to = 1.337,
                    remaining_amount_greater_then = 1.337,
                    payment_frequency = [
                        ''
                        ],
                    payment_method = 'sct',
                    is_overdue = True,
                    is_ready_for_collection = True,
                    property_group_ids = [
                        ''
                        ],
                    collection_case_id = '',
                    payment_reference = '',
                    customer_group_id = '',
                    apply_filters_over_included_ids = True,
                    flex_search = '',
                    include_only_ids = [
                        ''
                        ],
                    exclude_ids = [
                        ''
                        ],
                    page_size = 56, ),
                quick_filter = '',
                reason = ''
            )
        else:
            return BulkCancelPaymentPlanRequest(
        )
        """

    def testBulkCancelPaymentPlanRequest(self):
        """Test BulkCancelPaymentPlanRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
