# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.get_incoming_banking_transactions_query_params import GetIncomingBankingTransactionsQueryParams

class TestGetIncomingBankingTransactionsQueryParams(unittest.TestCase):
    """GetIncomingBankingTransactionsQueryParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIncomingBankingTransactionsQueryParams:
        """Test GetIncomingBankingTransactionsQueryParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIncomingBankingTransactionsQueryParams`
        """
        model = GetIncomingBankingTransactionsQueryParams()
        if include_optional:
            return GetIncomingBankingTransactionsQueryParams(
                flex_search = '',
                include_only_ids = [
                    ''
                    ],
                exclude_ids = [
                    ''
                    ],
                company_bank_account_id = '',
                mutation_date_time_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                mutation_date_time_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                opening_balance_date_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                opening_balance_date_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetIncomingBankingTransactionsQueryParams(
        )
        """

    def testGetIncomingBankingTransactionsQueryParams(self):
        """Test GetIncomingBankingTransactionsQueryParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
