# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.invoice_billing_configuration_suggestions_response_dto import InvoiceBillingConfigurationSuggestionsResponseDTO

class TestInvoiceBillingConfigurationSuggestionsResponseDTO(unittest.TestCase):
    """InvoiceBillingConfigurationSuggestionsResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceBillingConfigurationSuggestionsResponseDTO:
        """Test InvoiceBillingConfigurationSuggestionsResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceBillingConfigurationSuggestionsResponseDTO`
        """
        model = InvoiceBillingConfigurationSuggestionsResponseDTO()
        if include_optional:
            return InvoiceBillingConfigurationSuggestionsResponseDTO(
                advance_frequency = 'none',
                invoice_frequency = 'monthly',
                payment_terms_id = '',
                message = billing_client.models.localised_system_message_dto.LocalisedSystemMessageDTO(
                    key = null, 
                    message = '', 
                    message_values = [
                        billing_client.models.localised_system_message_dto_value.LocalisedSystemMessageDtoValue(
                            data_type = null, 
                            value = '', )
                        ], 
                    level = null, ),
                invoice_month = 56,
                invoice_day = 56,
                iban = '',
                company_bank_account_id = ''
            )
        else:
            return InvoiceBillingConfigurationSuggestionsResponseDTO(
        )
        """

    def testInvoiceBillingConfigurationSuggestionsResponseDTO(self):
        """Test InvoiceBillingConfigurationSuggestionsResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
