# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.paged_response_model_dtoof_incoming_mutation_dto import PagedResponseModelDTOOfIncomingMutationDTO

class TestPagedResponseModelDTOOfIncomingMutationDTO(unittest.TestCase):
    """PagedResponseModelDTOOfIncomingMutationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PagedResponseModelDTOOfIncomingMutationDTO:
        """Test PagedResponseModelDTOOfIncomingMutationDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PagedResponseModelDTOOfIncomingMutationDTO`
        """
        model = PagedResponseModelDTOOfIncomingMutationDTO()
        if include_optional:
            return PagedResponseModelDTOOfIncomingMutationDTO(
                results = [
                    billing_client.models.incoming_mutation_dto.IncomingMutationDTO(
                        incoming_banking_transaction_id = '',
                        transaction_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        type = 'incomingtransfer',
                        status = 'created',
                        amount = 1.337,
                        display_amount = 1.337,
                        is_manual_match = True,
                        details = billing_client.models.base_incoming_mutation_details_dto.BaseIncomingMutationDetailsDTO(),
                        reference_analysis = billing_client.models.incoming_mutation_reference_analysis_dto.IncomingMutationReferenceAnalysisDTO(
                            raw_reference = '',
                            kind = 'none',
                            tokens = [
                                billing_client.models.incoming_mutation_reference_token_dto.IncomingMutationReferenceTokenDTO(
                                    value = '',
                                    start = 56,
                                    length = 56, )
                                ],
                            suggested_customer_id = '',
                            suggested_transaction_ids = [
                                ''
                                ],
                            amount_matches = True,
                            iban_matches = True,
                            auto_match_applied = True,
                            reason = '',
                            analyzed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                        errors = [
                            billing_client.models.localised_error_dto.LocalisedErrorDTO(
                                key = 56,
                                correlation_id = '',
                                message = '',
                                message_values = [
                                    billing_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                        data_type = 'text',
                                        value = '',
                                        capitalize = True, )
                                    ], )
                            ],
                        organisation_id = '',
                        id = '',
                        entity_type = 'none',
                        created_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        discriminator = '',
                        _etag = '',
                        has_errors = True,
                        is_read_only = True, )
                    ],
                has_next_page = True,
                next_page_token = '',
                total_records = 56,
                sortable_fields = [
                    ''
                    ],
                aggregate_details = [
                    billing_client.models.aggregate_details_dto.AggregateDetailsDTO(
                        code = '',
                        translation = '',
                        value = 1.337,
                        value_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PagedResponseModelDTOOfIncomingMutationDTO(
        )
        """

    def testPagedResponseModelDTOOfIncomingMutationDTO(self):
        """Test PagedResponseModelDTOOfIncomingMutationDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
