# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.api_response_dtoof_deferred_off_session_collect_preview_dto import ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO

class TestApiResponseDTOOfDeferredOffSessionCollectPreviewDTO(unittest.TestCase):
    """ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO:
        """Test ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO`
        """
        model = ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO()
        if include_optional:
            return ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO(
                data = billing_client.models.deferred_off_session_collect_preview_dto.DeferredOffSessionCollectPreviewDTO(
                    number_of_invoices = 56,
                    total_amount = 1.337, ),
                errors = [
                    billing_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = 56,
                        correlation_id = '',
                        message = '',
                        message_values = [
                            billing_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = 'text',
                                value = '',
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True
            )
        else:
            return ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO(
        )
        """

    def testApiResponseDTOOfDeferredOffSessionCollectPreviewDTO(self):
        """Test ApiResponseDTOOfDeferredOffSessionCollectPreviewDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
