# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.base_incoming_mutation_details_dto_incoming_payment_request_mutation_confirmation_details_dto import BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO

class TestBaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO(unittest.TestCase):
    """BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO:
        """Test BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO`
        """
        model = BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO()
        if include_optional:
            return BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO(
                type = 'IncomingPaymentRequestMutationConfirmationDetailsDTO',
                payment_request_outgoing_mutation_id = '',
                account_holder = '',
                description = '',
                matching_outgoing_banking_transaction_id = '',
                matching_outgoing_banking_transaction_identification = '',
                iban = '',
                iban_confirmation_status = 'unspecified',
                is_iban_confirmed_on_transaction = True
            )
        else:
            return BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO(
        )
        """

    def testBaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO(self):
        """Test BaseIncomingMutationDetailsDTOIncomingPaymentRequestMutationConfirmationDetailsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
