# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.payment_bank_outgoing_origin_dto import PaymentBankOutgoingOriginDTO

class TestPaymentBankOutgoingOriginDTO(unittest.TestCase):
    """PaymentBankOutgoingOriginDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentBankOutgoingOriginDTO:
        """Test PaymentBankOutgoingOriginDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentBankOutgoingOriginDTO`
        """
        model = PaymentBankOutgoingOriginDTO()
        if include_optional:
            return PaymentBankOutgoingOriginDTO(
                outgoing_mutation_id = '',
                outgoing_banking_transaction_id = '',
                outgoing_banking_transaction_identification = '',
                is_confirmed_by_bank = True
            )
        else:
            return PaymentBankOutgoingOriginDTO(
        )
        """

    def testPaymentBankOutgoingOriginDTO(self):
        """Test PaymentBankOutgoingOriginDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
