# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.payment_rail import PaymentRail

class TestPaymentRail(unittest.TestCase):
    """PaymentRail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentRail(self):
        """Test PaymentRail"""
        # inst = PaymentRail()

if __name__ == '__main__':
    unittest.main()
