# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.billing_relation_dto_paged_response_model_dto import BillingRelationDTOPagedResponseModelDTO

class TestBillingRelationDTOPagedResponseModelDTO(unittest.TestCase):
    """BillingRelationDTOPagedResponseModelDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingRelationDTOPagedResponseModelDTO:
        """Test BillingRelationDTOPagedResponseModelDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingRelationDTOPagedResponseModelDTO`
        """
        model = BillingRelationDTOPagedResponseModelDTO()
        if include_optional:
            return BillingRelationDTOPagedResponseModelDTO(
                results = [
                    billing_client.models.billing_relation_dto.BillingRelationDTO(
                        id = '', 
                        debtor = null, 
                        payment_terms_id = '', 
                        payment_method = null, 
                        advance_details = null, 
                        invoice_details = null, 
                        contract = null, 
                        contract_start_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        contract_end_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        block_details = null, 
                        expect_advances_to_be_imported_periodically = True, 
                        time_zone = '', )
                    ],
                has_next_page = True,
                next_page_token = '',
                total_records = 56,
                sortable_fields = [
                    ''
                    ],
                aggregate_details = [
                    billing_client.models.aggregate_details_dto.AggregateDetailsDTO(
                        code = '', 
                        translation = '', 
                        value = 1.337, 
                        value_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return BillingRelationDTOPagedResponseModelDTO(
        )
        """

    def testBillingRelationDTOPagedResponseModelDTO(self):
        """Test BillingRelationDTOPagedResponseModelDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
