# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.api.incoming_banking_transactions_api import IncomingBankingTransactionsApi


class TestIncomingBankingTransactionsApi(unittest.TestCase):
    """IncomingBankingTransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IncomingBankingTransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_incomingbankingtransactions_incomingbankingtransactionid(self) -> None:
        """Test case for delete_incomingbankingtransactions_incomingbankingtransactionid

        Deletes a specific incoming banking transaction by its ID.
        """
        pass

    def test_get_incomingbankingtransactions(self) -> None:
        """Test case for get_incomingbankingtransactions

        Retrieves all incoming banking transactions based on the provided query parameters and filters.
        """
        pass

    def test_get_incomingbankingtransactions_incomingbankingtransactionid(self) -> None:
        """Test case for get_incomingbankingtransactions_incomingbankingtransactionid

        Retrieves a specific incoming banking transaction by its ID.
        """
        pass

    def test_get_incomingbankingtransactions_incomingbankingtransactionid_insights(self) -> None:
        """Test case for get_incomingbankingtransactions_incomingbankingtransactionid_insights

        Retrieves insights for a specific incoming banking transaction.
        """
        pass

    def test_get_incomingbankingtransactions_incomingbankingtransactionid_mutations(self) -> None:
        """Test case for get_incomingbankingtransactions_incomingbankingtransactionid_mutations

        Retrieves all incoming mutations for a specific incoming banking transaction.
        """
        pass

    def test_get_incomingbankingtransactions_incomingbankingtransactionid_mutations_overv(self) -> None:
        """Test case for get_incomingbankingtransactions_incomingbankingtransactionid_mutations_overv

        Retrieves an overview count of incoming mutations for a specific incoming banking transaction.
        """
        pass

    def test_get_incomingbankingtransactions_insights_lastupdated(self) -> None:
        """Test case for get_incomingbankingtransactions_insights_lastupdated

        Retrieves last updated insights about the incoming banking transactions, grouped by company bank account
        """
        pass

    def test_get_incomingbankingtransactions_overviewcount(self) -> None:
        """Test case for get_incomingbankingtransactions_overviewcount

        Retrieves an overview count of all incoming banking transactions based on the provided query parameters.
        """
        pass

    def test_post_incomingbankingtransactions_bulk_delete(self) -> None:
        """Test case for post_incomingbankingtransactions_bulk_delete

        Bulk deletes incoming banking transactions based on the provided request.
        """
        pass

    def test_post_incomingbankingtransactions_bulk_process(self) -> None:
        """Test case for post_incomingbankingtransactions_bulk_process

        Bulk processes incoming banking transactions based on the provided request.
        """
        pass

    def test_post_incomingbankingtransactions_export(self) -> None:
        """Test case for post_incomingbankingtransactions_export

        Exports incoming banking transactions based on the provided request.
        """
        pass

    def test_post_incomingbankingtransactions_incomingbankingtransactionid_mutations_igno(self) -> None:
        """Test case for post_incomingbankingtransactions_incomingbankingtransactionid_mutations_igno

        Ignores multiple incoming mutations for a specific incoming banking transaction.
        """
        pass

    def test_post_incomingbankingtransactions_incomingbankingtransactionid_process(self) -> None:
        """Test case for post_incomingbankingtransactions_incomingbankingtransactionid_process

        Processes a specific incoming banking transaction by its ID.
        """
        pass

    def test_post_incomingbankingtransactions_incomingbankingtransactionid_updateibanconf(self) -> None:
        """Test case for post_incomingbankingtransactions_incomingbankingtransactionid_updateibanconf

        Updates the IBAN confirmation of an Iban used in a specific incoming banking transaction.
        """
        pass


if __name__ == '__main__':
    unittest.main()
