# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.invoice_billing_configuration_suggestions_response_dto_api_response_dto import InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO

class TestInvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO(unittest.TestCase):
    """InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO:
        """Test InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO`
        """
        model = InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO()
        if include_optional:
            return InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO(
                errors = [
                    billing_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = null, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            billing_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = null, 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True,
                data = billing_client.models.invoice_billing_configuration_suggestions_response_dto.InvoiceBillingConfigurationSuggestionsResponseDTO(
                    advance_frequency = null, 
                    invoice_frequency = null, 
                    payment_terms_id = '', 
                    message = null, 
                    invoice_month = 56, 
                    invoice_day = 56, 
                    iban = '', 
                    company_bank_account_id = '', )
            )
        else:
            return InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO(
        )
        """

    def testInvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO(self):
        """Test InvoiceBillingConfigurationSuggestionsResponseDTOApiResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
