# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.api_response_dtoof_cust_aging_overview_count_response_dto import ApiResponseDTOOfCustAgingOverviewCountResponseDTO

class TestApiResponseDTOOfCustAgingOverviewCountResponseDTO(unittest.TestCase):
    """ApiResponseDTOOfCustAgingOverviewCountResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseDTOOfCustAgingOverviewCountResponseDTO:
        """Test ApiResponseDTOOfCustAgingOverviewCountResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseDTOOfCustAgingOverviewCountResponseDTO`
        """
        model = ApiResponseDTOOfCustAgingOverviewCountResponseDTO()
        if include_optional:
            return ApiResponseDTOOfCustAgingOverviewCountResponseDTO(
                data = billing_client.models.cust_aging_overview_count_response_dto.CustAgingOverviewCountResponseDTO(
                    open_credits = 1.337, 
                    open_debits = 1.337, 
                    total_open_not_overdue = 1.337, 
                    total_overdue30_d = 1.337, 
                    total_overdue60_d = 1.337, 
                    total_overdue90_d = 1.337, 
                    total_overdue_over90_d = 1.337, 
                    total_collection_costs_open = 1.337, 
                    total_open = 1.337, ),
                errors = [
                    billing_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = 56, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            billing_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = 'text', 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True
            )
        else:
            return ApiResponseDTOOfCustAgingOverviewCountResponseDTO(
        )
        """

    def testApiResponseDTOOfCustAgingOverviewCountResponseDTO(self):
        """Test ApiResponseDTOOfCustAgingOverviewCountResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
