# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.api.outgoing_mutations_api import OutgoingMutationsApi


class TestOutgoingMutationsApi(unittest.TestCase):
    """OutgoingMutationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OutgoingMutationsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_outgoingmutations_outgoingmutationid(self) -> None:
        """Test case for delete_outgoingmutations_outgoingmutationid

        Deletes an outgoing mutation by ID.
        """
        pass

    def test_get_outgoingmutations_outgoingmutationid(self) -> None:
        """Test case for get_outgoingmutations_outgoingmutationid

        Gets an outgoing mutation by ID.
        """
        pass

    def test_get_outgoingmutations_search_outgoingmutationtype(self) -> None:
        """Test case for get_outgoingmutations_search_outgoingmutationtype

        Gets all outgoing mutations by type.
        """
        pass

    def test_post_outgoingmutations_bulk_delete(self) -> None:
        """Test case for post_outgoingmutations_bulk_delete

        Bulk deletes outgoing mutations.
        """
        pass

    def test_post_outgoingmutations_outgoingmutationid(self) -> None:
        """Test case for post_outgoingmutations_outgoingmutationid

        Updates an outgoing mutation.
        """
        pass


if __name__ == '__main__':
    unittest.main()
