# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.get_outgoing_mutations_query_params import GetOutgoingMutationsQueryParams

class TestGetOutgoingMutationsQueryParams(unittest.TestCase):
    """GetOutgoingMutationsQueryParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOutgoingMutationsQueryParams:
        """Test GetOutgoingMutationsQueryParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOutgoingMutationsQueryParams`
        """
        model = GetOutgoingMutationsQueryParams()
        if include_optional:
            return GetOutgoingMutationsQueryParams(
                flex_search = '',
                include_only_ids = [
                    ''
                    ],
                exclude_ids = [
                    ''
                    ],
                outgoing_banking_transaction_id = '',
                status = '',
                reference_type = ''
            )
        else:
            return GetOutgoingMutationsQueryParams(
        )
        """

    def testGetOutgoingMutationsQueryParams(self):
        """Test GetOutgoingMutationsQueryParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
