# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from billing_client.models.get_transactions_query_params import GetTransactionsQueryParams

class TestGetTransactionsQueryParams(unittest.TestCase):
    """GetTransactionsQueryParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTransactionsQueryParams:
        """Test GetTransactionsQueryParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTransactionsQueryParams`
        """
        model = GetTransactionsQueryParams()
        if include_optional:
            return GetTransactionsQueryParams(
                customeruuid = '',
                reference_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                period_start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                period_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hide_credits = True,
                only_overdue = True,
                only_open = True,
                property_group_id = '',
                company_bank_account_id = '',
                amount_sign = '',
                open_amount_minimum = 1.337,
                open_amount_maximum = 1.337,
                only_count = True,
                transaction_reference_type = '',
                invoice_types = [
                    ''
                    ],
                payment_plan_id = '',
                exclude_active_payment_plans = True,
                only_in_payment_plan = True,
                only_in_collection_case = True,
                transaction_type = 'invoice',
                transaction_types = [
                    ''
                    ],
                account_export_status = 'pending',
                only_credit_billing = True,
                prepayment_account_id = '',
                flex_search = '',
                include_only_ids = [
                    ''
                    ],
                exclude_ids = [
                    ''
                    ],
                page_size = 56
            )
        else:
            return GetTransactionsQueryParams(
        )
        """

    def testGetTransactionsQueryParams(self):
        """Test GetTransactionsQueryParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
