# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.gbr_regional_regulations_configuration_dto_api_response_dto import GBRRegionalRegulationsConfigurationDTOApiResponseDTO

class TestGBRRegionalRegulationsConfigurationDTOApiResponseDTO(unittest.TestCase):
    """GBRRegionalRegulationsConfigurationDTOApiResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GBRRegionalRegulationsConfigurationDTOApiResponseDTO:
        """Test GBRRegionalRegulationsConfigurationDTOApiResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GBRRegionalRegulationsConfigurationDTOApiResponseDTO`
        """
        model = GBRRegionalRegulationsConfigurationDTOApiResponseDTO()
        if include_optional:
            return GBRRegionalRegulationsConfigurationDTOApiResponseDTO(
                errors = [
                    configuration_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = null, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            configuration_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = null, 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True,
                data = configuration_client.models.gbr_regional_regulations_configuration_dto.GBRRegionalRegulationsConfigurationDTO(
                    country_code = null, 
                    priority_register_parameters = null, )
            )
        else:
            return GBRRegionalRegulationsConfigurationDTOApiResponseDTO(
        )
        """

    def testGBRRegionalRegulationsConfigurationDTOApiResponseDTO(self):
        """Test GBRRegionalRegulationsConfigurationDTOApiResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
