# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.api_response_dtoof_paged_response_model_dtoof_time_of_use_calendar_dto import ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO

class TestApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO(unittest.TestCase):
    """ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO:
        """Test ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO`
        """
        model = ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO()
        if include_optional:
            return ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO(
                data = configuration_client.models.paged_response_model_dtoof_time_of_use_calendar_dto.PagedResponseModelDTOOfTimeOfUseCalendarDTO(
                    results = [
                        configuration_client.models.time_of_use_calendar_dto.TimeOfUseCalendarDTO(
                            code = '', 
                            weekdays = [
                                configuration_client.models.time_of_use_day_dto.TimeOfUseDayDTO(
                                    weekday_index = 56, 
                                    intervals = [
                                        configuration_client.models.time_of_use_interval_dto.TimeOfUseIntervalDTO(
                                            begin_minute_of_day = 56, 
                                            end_minute_of_day = 56, 
                                            time_of_use_type_code = '', )
                                        ], )
                                ], 
                            deleted = True, 
                            id = '', 
                            entity_type = 'none', 
                            created_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            discriminator = '', 
                            _etag = '', 
                            has_errors = True, 
                            is_read_only = True, )
                        ], 
                    has_next_page = True, 
                    next_page_token = '', 
                    total_records = 56, 
                    sortable_fields = [
                        ''
                        ], 
                    aggregate_details = [
                        configuration_client.models.aggregate_details_dto.AggregateDetailsDTO(
                            code = '', 
                            translation = '', 
                            value = 1.337, 
                            value_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], ),
                errors = [
                    configuration_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = 56, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            configuration_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = 'text', 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True
            )
        else:
            return ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO(
        )
        """

    def testApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO(self):
        """Test ApiResponseDTOOfPagedResponseModelDTOOfTimeOfUseCalendarDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
