# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.plugin_type import PluginType

class TestPluginType(unittest.TestCase):
    """PluginType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPluginType(self):
        """Test PluginType"""
        # inst = PluginType()

if __name__ == '__main__':
    unittest.main()
