# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.portal_advance_change_limit_dto import PortalAdvanceChangeLimitDTO

class TestPortalAdvanceChangeLimitDTO(unittest.TestCase):
    """PortalAdvanceChangeLimitDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PortalAdvanceChangeLimitDTO:
        """Test PortalAdvanceChangeLimitDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PortalAdvanceChangeLimitDTO`
        """
        model = PortalAdvanceChangeLimitDTO()
        if include_optional:
            return PortalAdvanceChangeLimitDTO(
                range_min = 1.337,
                range_max = 1.337,
                type = 'fixed'
            )
        else:
            return PortalAdvanceChangeLimitDTO(
        )
        """

    def testPortalAdvanceChangeLimitDTO(self):
        """Test PortalAdvanceChangeLimitDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
