# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.api_response_dtoof_list_of_billing_tariff_tree_dto import ApiResponseDTOOfListOfBillingTariffTreeDTO

class TestApiResponseDTOOfListOfBillingTariffTreeDTO(unittest.TestCase):
    """ApiResponseDTOOfListOfBillingTariffTreeDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseDTOOfListOfBillingTariffTreeDTO:
        """Test ApiResponseDTOOfListOfBillingTariffTreeDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseDTOOfListOfBillingTariffTreeDTO`
        """
        model = ApiResponseDTOOfListOfBillingTariffTreeDTO()
        if include_optional:
            return ApiResponseDTOOfListOfBillingTariffTreeDTO(
                data = [
                    configuration_client.models.billing_tariff_tree_dto.BillingTariffTreeDTO(
                        id = '', 
                        billing_item_id = '', 
                        product_id = '', 
                        activity_period = configuration_client.models.date_range.DateRange(
                            start_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            end_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        currently_active = True, 
                        nodes = [
                            configuration_client.models.billing_tariff_node_dto.BillingTariffNodeDTO(
                                billing_tariff_id = '', 
                                calculation_parameters = configuration_client.models.base_tariff_calculation_type_parameters_dto.BaseTariffCalculationTypeParametersDTO(), 
                                condition = configuration_client.models.base_tariff_condition_type_parameters_dto.BaseTariffConditionTypeParametersDTO(), )
                            ], )
                    ],
                errors = [
                    configuration_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = 56, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            configuration_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = 'text', 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True
            )
        else:
            return ApiResponseDTOOfListOfBillingTariffTreeDTO(
        )
        """

    def testApiResponseDTOOfListOfBillingTariffTreeDTO(self):
        """Test ApiResponseDTOOfListOfBillingTariffTreeDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
