# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.create_vat_codes_request import CreateVatCodesRequest

class TestCreateVatCodesRequest(unittest.TestCase):
    """CreateVatCodesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateVatCodesRequest:
        """Test CreateVatCodesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateVatCodesRequest`
        """
        model = CreateVatCodesRequest()
        if include_optional:
            return CreateVatCodesRequest(
                vat_codes = [
                    configuration_client.models.create_vat_code_request.CreateVatCodeRequest(
                        code = '',
                        description = '',
                        metadata = configuration_client.models.external_accounting_metadata_request.ExternalAccountingMetadataRequest(
                            source = '',
                            source_entity_id = '',
                            source_accounting_company_id = '', ), )
                    ]
            )
        else:
            return CreateVatCodesRequest(
        )
        """

    def testCreateVatCodesRequest(self):
        """Test CreateVatCodesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
