# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.base_bank_statement_matching_rule_dto_auto_confirm_iban_on_high_confidence_match_rule_dto import BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO

class TestBaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO(unittest.TestCase):
    """BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO:
        """Test BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO`
        """
        model = BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO()
        if include_optional:
            return BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO(
                type = 'AutoConfirmIbanOnHighConfidenceMatchRule',
                kind = '',
                enabled = True
            )
        else:
            return BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO(
        )
        """

    def testBaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO(self):
        """Test BaseBankStatementMatchingRuleDTOAutoConfirmIbanOnHighConfidenceMatchRuleDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
