# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.collection_email_template_dto import CollectionEmailTemplateDTO

class TestCollectionEmailTemplateDTO(unittest.TestCase):
    """CollectionEmailTemplateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionEmailTemplateDTO:
        """Test CollectionEmailTemplateDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionEmailTemplateDTO`
        """
        model = CollectionEmailTemplateDTO()
        if include_optional:
            return CollectionEmailTemplateDTO(
                file_name = '',
                use_case = 'pdf',
                use_build_in = True,
                custom_template_internal_file_path = '',
                custom_template_file_name = '',
                translation_status = 'defaulttranslation',
                subject = '',
                attachments = [
                    configuration_client.models.template_attachment_dto.TemplateAttachmentDTO(
                        id = '', 
                        internal_file_path = '', 
                        file_name = '', )
                    ]
            )
        else:
            return CollectionEmailTemplateDTO(
        )
        """

    def testCollectionEmailTemplateDTO(self):
        """Test CollectionEmailTemplateDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
