# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.annual_statement_origin import AnnualStatementOrigin

class TestAnnualStatementOrigin(unittest.TestCase):
    """AnnualStatementOrigin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnualStatementOrigin(self):
        """Test AnnualStatementOrigin"""
        # inst = AnnualStatementOrigin()

if __name__ == '__main__':
    unittest.main()
