# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.base_metering_import_format_dto_custom_csv_metering_import_format_dto import BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO

class TestBaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO(unittest.TestCase):
    """BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO:
        """Test BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO`
        """
        model = BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO()
        if include_optional:
            return BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO(
                type = 'customCsv',
                first_line_is_header = True,
                delimiter = ',',
                date_time_format = '',
                time_zone = '',
                culture = '',
                number_thousands_seperator = '',
                number_decimal_seperator = '',
                values = [
                    configuration_client.models.custom_csv_metering_value_dto.CustomCsvMeteringValueDTO(
                        measurement_path = '', 
                        period_end_date_time_path = '', 
                        period_start_date_time_path = '', 
                        attributes = [
                            configuration_client.models.custom_csv_metering_value_attribute_dto.CustomCsvMeteringValueAttributeDTO(
                                attribute_type = 'meterserialnumber', 
                                path = '', 
                                fixed_value = '', 
                                is_fixed = True, )
                            ], )
                    ]
            )
        else:
            return BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO(
                delimiter = ',',
                date_time_format = '',
                time_zone = '',
                number_decimal_seperator = '',
                values = [
                    configuration_client.models.custom_csv_metering_value_dto.CustomCsvMeteringValueDTO(
                        measurement_path = '', 
                        period_end_date_time_path = '', 
                        period_start_date_time_path = '', 
                        attributes = [
                            configuration_client.models.custom_csv_metering_value_attribute_dto.CustomCsvMeteringValueAttributeDTO(
                                attribute_type = 'meterserialnumber', 
                                path = '', 
                                fixed_value = '', 
                                is_fixed = True, )
                            ], )
                    ],
        )
        """

    def testBaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO(self):
        """Test BaseMeteringImportFormatDTOCustomCsvMeteringImportFormatDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
