# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.custom_csv_column_title_attribute_dto import CustomCsvColumnTitleAttributeDTO

class TestCustomCsvColumnTitleAttributeDTO(unittest.TestCase):
    """CustomCsvColumnTitleAttributeDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomCsvColumnTitleAttributeDTO:
        """Test CustomCsvColumnTitleAttributeDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomCsvColumnTitleAttributeDTO`
        """
        model = CustomCsvColumnTitleAttributeDTO()
        if include_optional:
            return CustomCsvColumnTitleAttributeDTO(
                attribute_type = 'meterserialnumber',
                segment_index = 56,
                fixed_value = '',
                is_fixed = True
            )
        else:
            return CustomCsvColumnTitleAttributeDTO(
                attribute_type = 'meterserialnumber',
                segment_index = 56,
                fixed_value = '',
        )
        """

    def testCustomCsvColumnTitleAttributeDTO(self):
        """Test CustomCsvColumnTitleAttributeDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
