# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.custom_entity_property_type_dto_paged_response_model_dto import CustomEntityPropertyTypeDTOPagedResponseModelDTO

class TestCustomEntityPropertyTypeDTOPagedResponseModelDTO(unittest.TestCase):
    """CustomEntityPropertyTypeDTOPagedResponseModelDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomEntityPropertyTypeDTOPagedResponseModelDTO:
        """Test CustomEntityPropertyTypeDTOPagedResponseModelDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomEntityPropertyTypeDTOPagedResponseModelDTO`
        """
        model = CustomEntityPropertyTypeDTOPagedResponseModelDTO()
        if include_optional:
            return CustomEntityPropertyTypeDTOPagedResponseModelDTO(
                results = [
                    configuration_client.models.custom_entity_property_type_dto.CustomEntityPropertyTypeDTO(
                        id = '', 
                        entity_type = null, 
                        created_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        discriminator = '', 
                        _etag = '', 
                        require_attention = True, 
                        has_errors = True, 
                        has_warnings = True, 
                        is_read_only = True, 
                        name = '', 
                        description = '', 
                        deleted = True, 
                        entity_subject_type = null, 
                        value_type = null, 
                        localisation_level = null, 
                        localised_fields = [
                            ''
                            ], 
                        translated_fields = {
                            'key' : {
                                'key' : ''
                                }
                            }, 
                        show_in_header = True, 
                        tag_color = null, )
                    ],
                has_next_page = True,
                next_page_token = '',
                total_records = 56,
                sortable_fields = [
                    ''
                    ],
                aggregate_details = [
                    configuration_client.models.aggregate_details_dto.AggregateDetailsDTO(
                        code = '', 
                        translation = '', 
                        value = 1.337, 
                        value_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return CustomEntityPropertyTypeDTOPagedResponseModelDTO(
        )
        """

    def testCustomEntityPropertyTypeDTOPagedResponseModelDTO(self):
        """Test CustomEntityPropertyTypeDTOPagedResponseModelDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
