# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.update_bank_account_request import UpdateBankAccountRequest

class TestUpdateBankAccountRequest(unittest.TestCase):
    """UpdateBankAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateBankAccountRequest:
        """Test UpdateBankAccountRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateBankAccountRequest`
        """
        model = UpdateBankAccountRequest()
        if include_optional:
            return UpdateBankAccountRequest(
                bic = '',
                account_holder = '',
                sepa_creditor_id = '',
                is_default = True
            )
        else:
            return UpdateBankAccountRequest(
        )
        """

    def testUpdateBankAccountRequest(self):
        """Test UpdateBankAccountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
