# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.api_response_dtoof_scenario_translation_list_dto import ApiResponseDTOOfScenarioTranslationListDTO

class TestApiResponseDTOOfScenarioTranslationListDTO(unittest.TestCase):
    """ApiResponseDTOOfScenarioTranslationListDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseDTOOfScenarioTranslationListDTO:
        """Test ApiResponseDTOOfScenarioTranslationListDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseDTOOfScenarioTranslationListDTO`
        """
        model = ApiResponseDTOOfScenarioTranslationListDTO()
        if include_optional:
            return ApiResponseDTOOfScenarioTranslationListDTO(
                data = configuration_client.models.scenario_translation_list_dto.ScenarioTranslationListDTO(
                    id = '', 
                    template_entity_type = 'none', 
                    template_entity_sub_type = '', 
                    scenario_translations = [
                        configuration_client.models.scenario_translation_dto.ScenarioTranslationDTO(
                            name = '', 
                            status = 'defaulttranslation', 
                            has_default_translation = True, 
                            translations = {
                                'key' : ''
                                }, 
                            use_cases = [
                                'pdf'
                                ], )
                        ], ),
                errors = [
                    configuration_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = 56, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            configuration_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = 'text', 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True
            )
        else:
            return ApiResponseDTOOfScenarioTranslationListDTO(
        )
        """

    def testApiResponseDTOOfScenarioTranslationListDTO(self):
        """Test ApiResponseDTOOfScenarioTranslationListDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
