# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.create_cost_units_request import CreateCostUnitsRequest

class TestCreateCostUnitsRequest(unittest.TestCase):
    """CreateCostUnitsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCostUnitsRequest:
        """Test CreateCostUnitsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCostUnitsRequest`
        """
        model = CreateCostUnitsRequest()
        if include_optional:
            return CreateCostUnitsRequest(
                cost_units = [
                    configuration_client.models.create_cost_unit_request.CreateCostUnitRequest(
                        code = '', 
                        description = '', 
                        metadata = null, )
                    ]
            )
        else:
            return CreateCostUnitsRequest(
        )
        """

    def testCreateCostUnitsRequest(self):
        """Test CreateCostUnitsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
