# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configuration_client.models.required_estimation_dto_list_api_response_dto import RequiredEstimationDTOListApiResponseDTO

class TestRequiredEstimationDTOListApiResponseDTO(unittest.TestCase):
    """RequiredEstimationDTOListApiResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequiredEstimationDTOListApiResponseDTO:
        """Test RequiredEstimationDTOListApiResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequiredEstimationDTOListApiResponseDTO`
        """
        model = RequiredEstimationDTOListApiResponseDTO()
        if include_optional:
            return RequiredEstimationDTOListApiResponseDTO(
                errors = [
                    configuration_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = null, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            configuration_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = null, 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True,
                data = [
                    configuration_client.models.required_estimation_dto.RequiredEstimationDTO(
                        billing_item_ids = [
                            ''
                            ], 
                        utility_type = null, 
                        unit_of_measure = null, 
                        metering_type = null, )
                    ]
            )
        else:
            return RequiredEstimationDTOListApiResponseDTO(
        )
        """

    def testRequiredEstimationDTOListApiResponseDTO(self):
        """Test RequiredEstimationDTOListApiResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
