# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.update_prepayment_accounts_external_references_request import UpdatePrepaymentAccountsExternalReferencesRequest

class TestUpdatePrepaymentAccountsExternalReferencesRequest(unittest.TestCase):
    """UpdatePrepaymentAccountsExternalReferencesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdatePrepaymentAccountsExternalReferencesRequest:
        """Test UpdatePrepaymentAccountsExternalReferencesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdatePrepaymentAccountsExternalReferencesRequest`
        """
        model = UpdatePrepaymentAccountsExternalReferencesRequest()
        if include_optional:
            return UpdatePrepaymentAccountsExternalReferencesRequest(
                external_references_for_prepayment_accounts = {
                    'key' : ''
                    }
            )
        else:
            return UpdatePrepaymentAccountsExternalReferencesRequest(
        )
        """

    def testUpdatePrepaymentAccountsExternalReferencesRequest(self):
        """Test UpdatePrepaymentAccountsExternalReferencesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
