# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.contracted_service_estimated_consumption_dto import ContractedServiceEstimatedConsumptionDTO

class TestContractedServiceEstimatedConsumptionDTO(unittest.TestCase):
    """ContractedServiceEstimatedConsumptionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractedServiceEstimatedConsumptionDTO:
        """Test ContractedServiceEstimatedConsumptionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractedServiceEstimatedConsumptionDTO`
        """
        model = ContractedServiceEstimatedConsumptionDTO()
        if include_optional:
            return ContractedServiceEstimatedConsumptionDTO(
                consumer_group_id = '',
                value = 1.337,
                unit_of_measure = 'none',
                metering_type = 'none',
                is_manual_entry = True
            )
        else:
            return ContractedServiceEstimatedConsumptionDTO(
        )
        """

    def testContractedServiceEstimatedConsumptionDTO(self):
        """Test ContractedServiceEstimatedConsumptionDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
