# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.property_group_overview_count_dto_api_response_dto import PropertyGroupOverviewCountDTOApiResponseDTO

class TestPropertyGroupOverviewCountDTOApiResponseDTO(unittest.TestCase):
    """PropertyGroupOverviewCountDTOApiResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertyGroupOverviewCountDTOApiResponseDTO:
        """Test PropertyGroupOverviewCountDTOApiResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PropertyGroupOverviewCountDTOApiResponseDTO`
        """
        model = PropertyGroupOverviewCountDTOApiResponseDTO()
        if include_optional:
            return PropertyGroupOverviewCountDTOApiResponseDTO(
                errors = [
                    masterdata_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = null, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            masterdata_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = null, 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True,
                data = masterdata_client.models.property_group_overview_count_dto.PropertyGroupOverviewCountDTO(
                    all = 56, )
            )
        else:
            return PropertyGroupOverviewCountDTOApiResponseDTO(
        )
        """

    def testPropertyGroupOverviewCountDTOApiResponseDTO(self):
        """Test PropertyGroupOverviewCountDTOApiResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
