# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.update_customer_portal_details_request import UpdateCustomerPortalDetailsRequest

class TestUpdateCustomerPortalDetailsRequest(unittest.TestCase):
    """UpdateCustomerPortalDetailsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCustomerPortalDetailsRequest:
        """Test UpdateCustomerPortalDetailsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCustomerPortalDetailsRequest`
        """
        model = UpdateCustomerPortalDetailsRequest()
        if include_optional:
            return UpdateCustomerPortalDetailsRequest(
                application_user_id = '',
                reset_password_token = '',
                confirm_account_token = '',
                email = '',
                send_communication = True
            )
        else:
            return UpdateCustomerPortalDetailsRequest(
        )
        """

    def testUpdateCustomerPortalDetailsRequest(self):
        """Test UpdateCustomerPortalDetailsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
