# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.property_group_contact_details_dto import PropertyGroupContactDetailsDTO

class TestPropertyGroupContactDetailsDTO(unittest.TestCase):
    """PropertyGroupContactDetailsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertyGroupContactDetailsDTO:
        """Test PropertyGroupContactDetailsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PropertyGroupContactDetailsDTO`
        """
        model = PropertyGroupContactDetailsDTO()
        if include_optional:
            return PropertyGroupContactDetailsDTO(
                email_address = '',
                telephone = '',
                website = '',
                telephone_interruptions = ''
            )
        else:
            return PropertyGroupContactDetailsDTO(
        )
        """

    def testPropertyGroupContactDetailsDTO(self):
        """Test PropertyGroupContactDetailsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
