# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.change_customer_communication_preferences_request import ChangeCustomerCommunicationPreferencesRequest

class TestChangeCustomerCommunicationPreferencesRequest(unittest.TestCase):
    """ChangeCustomerCommunicationPreferencesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeCustomerCommunicationPreferencesRequest:
        """Test ChangeCustomerCommunicationPreferencesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangeCustomerCommunicationPreferencesRequest`
        """
        model = ChangeCustomerCommunicationPreferencesRequest()
        if include_optional:
            return ChangeCustomerCommunicationPreferencesRequest(
                communication_preferences = masterdata_client.models.customer_communication_preferences_request.CustomerCommunicationPreferencesRequest(
                    culture = null, 
                    invoice_communication_preferences = [
                        masterdata_client.models.customer_invoice_communication_preferences_request.CustomerInvoiceCommunicationPreferencesRequest(
                            invoice_type = null, 
                            communication_type = null, )
                        ], 
                    annual_statement_communication_preference = null, 
                    collection_flow_id = '', )
            )
        else:
            return ChangeCustomerCommunicationPreferencesRequest(
        )
        """

    def testChangeCustomerCommunicationPreferencesRequest(self):
        """Test ChangeCustomerCommunicationPreferencesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
