# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.cost_unit_mapping_overview_count_response_dto import CostUnitMappingOverviewCountResponseDTO

class TestCostUnitMappingOverviewCountResponseDTO(unittest.TestCase):
    """CostUnitMappingOverviewCountResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CostUnitMappingOverviewCountResponseDTO:
        """Test CostUnitMappingOverviewCountResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CostUnitMappingOverviewCountResponseDTO`
        """
        model = CostUnitMappingOverviewCountResponseDTO()
        if include_optional:
            return CostUnitMappingOverviewCountResponseDTO(
                customer_groups = 56
            )
        else:
            return CostUnitMappingOverviewCountResponseDTO(
        )
        """

    def testCostUnitMappingOverviewCountResponseDTO(self):
        """Test CostUnitMappingOverviewCountResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
