# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.advance_frequency import AdvanceFrequency

class TestAdvanceFrequency(unittest.TestCase):
    """AdvanceFrequency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdvanceFrequency(self):
        """Test AdvanceFrequency"""
        # inst = AdvanceFrequency()

if __name__ == '__main__':
    unittest.main()
