# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.paged_response_model_dtoof_project_code_mapping_item_dto import PagedResponseModelDTOOfProjectCodeMappingItemDTO

class TestPagedResponseModelDTOOfProjectCodeMappingItemDTO(unittest.TestCase):
    """PagedResponseModelDTOOfProjectCodeMappingItemDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PagedResponseModelDTOOfProjectCodeMappingItemDTO:
        """Test PagedResponseModelDTOOfProjectCodeMappingItemDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PagedResponseModelDTOOfProjectCodeMappingItemDTO`
        """
        model = PagedResponseModelDTOOfProjectCodeMappingItemDTO()
        if include_optional:
            return PagedResponseModelDTOOfProjectCodeMappingItemDTO(
                results = [
                    masterdata_client.models.project_code_mapping_item_dto.ProjectCodeMappingItemDTO(
                        name = '', 
                        accounting_code = masterdata_client.models.accounting_code_link_dto.AccountingCodeLinkDTO(
                            id = '', 
                            code = '', 
                            description = '', 
                            source_references = [
                                masterdata_client.models.external_accounting_reference_dto.ExternalAccountingReferenceDTO(
                                    source_entity_id = '', 
                                    source_accounting_company_id = '', )
                                ], ), 
                        accounting_status = 'unlinked', 
                        service_location_ids = [
                            ''
                            ], 
                        id = '', 
                        entity_type = 'none', 
                        created_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        discriminator = '', 
                        _etag = '', 
                        has_errors = True, 
                        is_read_only = True, )
                    ],
                has_next_page = True,
                next_page_token = '',
                total_records = 56,
                sortable_fields = [
                    ''
                    ],
                aggregate_details = [
                    masterdata_client.models.aggregate_details_dto.AggregateDetailsDTO(
                        code = '', 
                        translation = '', 
                        value = 1.337, 
                        value_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PagedResponseModelDTOOfProjectCodeMappingItemDTO(
        )
        """

    def testPagedResponseModelDTOOfProjectCodeMappingItemDTO(self):
        """Test PagedResponseModelDTOOfProjectCodeMappingItemDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
