# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from masterdata_client.models.plugin_feed_activity_type import PluginFeedActivityType

class TestPluginFeedActivityType(unittest.TestCase):
    """PluginFeedActivityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPluginFeedActivityType(self):
        """Test PluginFeedActivityType"""
        # inst = PluginFeedActivityType()

if __name__ == '__main__':
    unittest.main()
