# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from billing_client.models.annual_statement_status import AnnualStatementStatus
from billing_client.models.debtor_dto import DebtorDTO
from billing_client.models.entity_subject_type import EntitySubjectType
from billing_client.models.localised_error_dto import LocalisedErrorDTO
from billing_client.models.sent_status import SentStatus
from typing import Optional, Set
from typing_extensions import Self

class AnnualStatementDTO(BaseModel):
    """
    AnnualStatementDTO
    """ # noqa: E501
    annual_statement_number: Optional[StrictStr] = Field(default=None, alias="annualStatementNumber")
    year: Optional[StrictInt] = None
    version: Optional[StrictInt] = None
    start_date_time: Optional[datetime] = Field(default=None, alias="startDateTime")
    end_date_time: Optional[datetime] = Field(default=None, alias="endDateTime")
    status: Optional[AnnualStatementStatus] = None
    generation_date: Optional[datetime] = Field(default=None, alias="generationDate")
    sent: Optional[SentStatus] = None
    failure_reason_code: Optional[LocalisedErrorDTO] = Field(default=None, alias="failureReasonCode")
    failure_details: Optional[StrictStr] = Field(default=None, alias="failureDetails")
    supports_external_printing: Optional[StrictBool] = Field(default=None, alias="supportsExternalPrinting")
    attachment_id: Optional[StrictStr] = Field(default=None, alias="attachmentId")
    debtor: Optional[DebtorDTO] = None
    organisation_id: Optional[StrictStr] = Field(default=None, alias="organisationId")
    id: Optional[StrictStr] = None
    entity_type: Optional[EntitySubjectType] = Field(default=None, alias="entityType")
    created_date_time: Optional[datetime] = Field(default=None, alias="createdDateTime")
    discriminator: Optional[StrictStr] = None
    etag: Optional[StrictStr] = Field(default=None, alias="_etag")
    has_errors: Optional[StrictBool] = Field(default=None, alias="hasErrors")
    is_read_only: Optional[StrictBool] = Field(default=None, alias="isReadOnly")
    __properties: ClassVar[List[str]] = ["annualStatementNumber", "year", "version", "startDateTime", "endDateTime", "status", "generationDate", "sent", "failureReasonCode", "failureDetails", "supportsExternalPrinting", "attachmentId", "debtor", "organisationId", "id", "entityType", "createdDateTime", "discriminator", "_etag", "hasErrors", "isReadOnly"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnnualStatementDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of failure_reason_code
        if self.failure_reason_code:
            _dict['failureReasonCode'] = self.failure_reason_code.to_dict()
        # override the default output from pydantic by calling `to_dict()` of debtor
        if self.debtor:
            _dict['debtor'] = self.debtor.to_dict()
        # set to None if annual_statement_number (nullable) is None
        # and model_fields_set contains the field
        if self.annual_statement_number is None and "annual_statement_number" in self.model_fields_set:
            _dict['annualStatementNumber'] = None

        # set to None if failure_reason_code (nullable) is None
        # and model_fields_set contains the field
        if self.failure_reason_code is None and "failure_reason_code" in self.model_fields_set:
            _dict['failureReasonCode'] = None

        # set to None if failure_details (nullable) is None
        # and model_fields_set contains the field
        if self.failure_details is None and "failure_details" in self.model_fields_set:
            _dict['failureDetails'] = None

        # set to None if attachment_id (nullable) is None
        # and model_fields_set contains the field
        if self.attachment_id is None and "attachment_id" in self.model_fields_set:
            _dict['attachmentId'] = None

        # set to None if debtor (nullable) is None
        # and model_fields_set contains the field
        if self.debtor is None and "debtor" in self.model_fields_set:
            _dict['debtor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnnualStatementDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "annualStatementNumber": obj.get("annualStatementNumber"),
            "year": obj.get("year"),
            "version": obj.get("version"),
            "startDateTime": obj.get("startDateTime"),
            "endDateTime": obj.get("endDateTime"),
            "status": obj.get("status"),
            "generationDate": obj.get("generationDate"),
            "sent": obj.get("sent"),
            "failureReasonCode": LocalisedErrorDTO.from_dict(obj["failureReasonCode"]) if obj.get("failureReasonCode") is not None else None,
            "failureDetails": obj.get("failureDetails"),
            "supportsExternalPrinting": obj.get("supportsExternalPrinting"),
            "attachmentId": obj.get("attachmentId"),
            "debtor": DebtorDTO.from_dict(obj["debtor"]) if obj.get("debtor") is not None else None,
            "organisationId": obj.get("organisationId"),
            "id": obj.get("id"),
            "entityType": obj.get("entityType"),
            "createdDateTime": obj.get("createdDateTime"),
            "discriminator": obj.get("discriminator"),
            "_etag": obj.get("_etag"),
            "hasErrors": obj.get("hasErrors"),
            "isReadOnly": obj.get("isReadOnly")
        })
        return _obj
