# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from billing_client.models.accounting_export_provider_type import AccountingExportProviderType
from billing_client.models.berger_levrault_custom_entity_property_settings_request_dto import BergerLevraultCustomEntityPropertySettingsRequestDTO
from billing_client.models.ssh_authentication_method import SshAuthenticationMethod
from typing import Optional, Set
from typing_extensions import Self

class BaseAccountingExportProviderSettingsDTOBergerLevraultEseditProviderSettingsDTO(BaseModel):
    """
    BaseAccountingExportProviderSettingsDTOBergerLevraultEseditProviderSettingsDTO
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, alias="__type")
    provider_type: Optional[AccountingExportProviderType] = Field(default=None, alias="providerType")
    host: Optional[StrictStr]
    port: StrictInt
    user_name: Optional[StrictStr] = Field(alias="userName")
    password: Optional[StrictStr] = None
    directory: Optional[StrictStr]
    authentication_method: SshAuthenticationMethod = Field(alias="authenticationMethod")
    public_key: Optional[StrictStr] = Field(default=None, alias="publicKey")
    unc: Optional[StrictStr] = None
    budget_code: Optional[StrictStr] = Field(alias="budgetCode")
    structure_code: Optional[StrictStr] = Field(alias="structureCode")
    movement_code: Optional[StrictStr] = Field(alias="movementCode")
    custom_entity_property_settings: Optional[BergerLevraultCustomEntityPropertySettingsRequestDTO] = Field(default=None, alias="customEntityPropertySettings")
    __properties: ClassVar[List[str]] = ["__type", "providerType", "host", "port", "userName", "password", "directory", "authenticationMethod", "publicKey", "unc", "budgetCode", "structureCode", "movementCode", "customEntityPropertySettings"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BergerLevraultEseditProviderSettingsDTO']):
            raise ValueError("must be one of enum values ('BergerLevraultEseditProviderSettingsDTO')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BaseAccountingExportProviderSettingsDTOBergerLevraultEseditProviderSettingsDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom_entity_property_settings
        if self.custom_entity_property_settings:
            _dict['customEntityPropertySettings'] = self.custom_entity_property_settings.to_dict()
        # set to None if host (nullable) is None
        # and model_fields_set contains the field
        if self.host is None and "host" in self.model_fields_set:
            _dict['host'] = None

        # set to None if user_name (nullable) is None
        # and model_fields_set contains the field
        if self.user_name is None and "user_name" in self.model_fields_set:
            _dict['userName'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        # set to None if directory (nullable) is None
        # and model_fields_set contains the field
        if self.directory is None and "directory" in self.model_fields_set:
            _dict['directory'] = None

        # set to None if public_key (nullable) is None
        # and model_fields_set contains the field
        if self.public_key is None and "public_key" in self.model_fields_set:
            _dict['publicKey'] = None

        # set to None if unc (nullable) is None
        # and model_fields_set contains the field
        if self.unc is None and "unc" in self.model_fields_set:
            _dict['unc'] = None

        # set to None if budget_code (nullable) is None
        # and model_fields_set contains the field
        if self.budget_code is None and "budget_code" in self.model_fields_set:
            _dict['budgetCode'] = None

        # set to None if structure_code (nullable) is None
        # and model_fields_set contains the field
        if self.structure_code is None and "structure_code" in self.model_fields_set:
            _dict['structureCode'] = None

        # set to None if movement_code (nullable) is None
        # and model_fields_set contains the field
        if self.movement_code is None and "movement_code" in self.model_fields_set:
            _dict['movementCode'] = None

        # set to None if custom_entity_property_settings (nullable) is None
        # and model_fields_set contains the field
        if self.custom_entity_property_settings is None and "custom_entity_property_settings" in self.model_fields_set:
            _dict['customEntityPropertySettings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BaseAccountingExportProviderSettingsDTOBergerLevraultEseditProviderSettingsDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "__type": obj.get("__type"),
            "providerType": obj.get("providerType"),
            "host": obj.get("host"),
            "port": obj.get("port"),
            "userName": obj.get("userName"),
            "password": obj.get("password"),
            "directory": obj.get("directory"),
            "authenticationMethod": obj.get("authenticationMethod"),
            "publicKey": obj.get("publicKey"),
            "unc": obj.get("unc"),
            "budgetCode": obj.get("budgetCode"),
            "structureCode": obj.get("structureCode"),
            "movementCode": obj.get("movementCode"),
            "customEntityPropertySettings": BergerLevraultCustomEntityPropertySettingsRequestDTO.from_dict(obj["customEntityPropertySettings"]) if obj.get("customEntityPropertySettings") is not None else None
        })
        return _obj


