# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from billing_client.models.get_invoices_query_params import GetInvoicesQueryParams
from typing import Optional, Set
from typing_extensions import Self

class BaseAccountingExportRunParametersDTOBergerLevraultEseditParametersDTO(BaseModel):
    """
    BaseAccountingExportRunParametersDTOBergerLevraultEseditParametersDTO
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, alias="__type")
    period_start: Optional[datetime] = Field(default=None, alias="periodStart")
    period_end: Optional[datetime] = Field(default=None, alias="periodEnd")
    var_query_params: Optional[GetInvoicesQueryParams] = Field(default=None, alias="queryParams")
    mark_as_exported: Optional[StrictBool] = Field(default=None, alias="markAsExported")
    quick_filter: Optional[StrictStr] = Field(default=None, alias="quickFilter")
    __properties: ClassVar[List[str]] = ["__type", "periodStart", "periodEnd", "queryParams", "markAsExported", "quickFilter"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BergerLevraultEseditParametersDTO']):
            raise ValueError("must be one of enum values ('BergerLevraultEseditParametersDTO')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BaseAccountingExportRunParametersDTOBergerLevraultEseditParametersDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_query_params
        if self.var_query_params:
            _dict['queryParams'] = self.var_query_params.to_dict()
        # set to None if period_start (nullable) is None
        # and model_fields_set contains the field
        if self.period_start is None and "period_start" in self.model_fields_set:
            _dict['periodStart'] = None

        # set to None if period_end (nullable) is None
        # and model_fields_set contains the field
        if self.period_end is None and "period_end" in self.model_fields_set:
            _dict['periodEnd'] = None

        # set to None if var_query_params (nullable) is None
        # and model_fields_set contains the field
        if self.var_query_params is None and "var_query_params" in self.model_fields_set:
            _dict['queryParams'] = None

        # set to None if quick_filter (nullable) is None
        # and model_fields_set contains the field
        if self.quick_filter is None and "quick_filter" in self.model_fields_set:
            _dict['quickFilter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BaseAccountingExportRunParametersDTOBergerLevraultEseditParametersDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "__type": obj.get("__type"),
            "periodStart": obj.get("periodStart"),
            "periodEnd": obj.get("periodEnd"),
            "queryParams": GetInvoicesQueryParams.from_dict(obj["queryParams"]) if obj.get("queryParams") is not None else None,
            "markAsExported": obj.get("markAsExported"),
            "quickFilter": obj.get("quickFilter")
        })
        return _obj


