# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from billing_client.models.base_incoming_mutation_details_dto import BaseIncomingMutationDetailsDTO
from billing_client.models.entity_subject_type import EntitySubjectType
from billing_client.models.incoming_mutation_reference_analysis_dto import IncomingMutationReferenceAnalysisDTO
from billing_client.models.incoming_mutation_status import IncomingMutationStatus
from billing_client.models.incoming_mutation_type import IncomingMutationType
from billing_client.models.localised_error_dto import LocalisedErrorDTO
from typing import Optional, Set
from typing_extensions import Self

class IncomingMutationDTO(BaseModel):
    """
    IncomingMutationDTO
    """ # noqa: E501
    incoming_banking_transaction_id: Optional[StrictStr] = Field(default=None, alias="incomingBankingTransactionId")
    transaction_date: Optional[datetime] = Field(default=None, alias="transactionDate")
    type: Optional[IncomingMutationType] = None
    status: Optional[IncomingMutationStatus] = None
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    display_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="displayAmount")
    is_manual_match: Optional[StrictBool] = Field(default=None, alias="isManualMatch")
    details: Optional[BaseIncomingMutationDetailsDTO] = None
    reference_analysis: Optional[IncomingMutationReferenceAnalysisDTO] = Field(default=None, alias="referenceAnalysis")
    errors: Optional[List[LocalisedErrorDTO]] = None
    organisation_id: Optional[StrictStr] = Field(default=None, alias="organisationId")
    id: Optional[StrictStr] = None
    entity_type: Optional[EntitySubjectType] = Field(default=None, alias="entityType")
    created_date_time: Optional[datetime] = Field(default=None, alias="createdDateTime")
    discriminator: Optional[StrictStr] = None
    etag: Optional[StrictStr] = Field(default=None, alias="_etag")
    has_errors: Optional[StrictBool] = Field(default=None, alias="hasErrors")
    is_read_only: Optional[StrictBool] = Field(default=None, alias="isReadOnly")
    __properties: ClassVar[List[str]] = ["incomingBankingTransactionId", "transactionDate", "type", "status", "amount", "displayAmount", "isManualMatch", "details", "referenceAnalysis", "errors", "organisationId", "id", "entityType", "createdDateTime", "discriminator", "_etag", "hasErrors", "isReadOnly"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IncomingMutationDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of details
        if self.details:
            _dict['details'] = self.details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reference_analysis
        if self.reference_analysis:
            _dict['referenceAnalysis'] = self.reference_analysis.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['errors'] = _items
        # set to None if incoming_banking_transaction_id (nullable) is None
        # and model_fields_set contains the field
        if self.incoming_banking_transaction_id is None and "incoming_banking_transaction_id" in self.model_fields_set:
            _dict['incomingBankingTransactionId'] = None

        # set to None if details (nullable) is None
        # and model_fields_set contains the field
        if self.details is None and "details" in self.model_fields_set:
            _dict['details'] = None

        # set to None if reference_analysis (nullable) is None
        # and model_fields_set contains the field
        if self.reference_analysis is None and "reference_analysis" in self.model_fields_set:
            _dict['referenceAnalysis'] = None

        # set to None if errors (nullable) is None
        # and model_fields_set contains the field
        if self.errors is None and "errors" in self.model_fields_set:
            _dict['errors'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IncomingMutationDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "incomingBankingTransactionId": obj.get("incomingBankingTransactionId"),
            "transactionDate": obj.get("transactionDate"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "amount": obj.get("amount"),
            "displayAmount": obj.get("displayAmount"),
            "isManualMatch": obj.get("isManualMatch"),
            "details": BaseIncomingMutationDetailsDTO.from_dict(obj["details"]) if obj.get("details") is not None else None,
            "referenceAnalysis": IncomingMutationReferenceAnalysisDTO.from_dict(obj["referenceAnalysis"]) if obj.get("referenceAnalysis") is not None else None,
            "errors": [LocalisedErrorDTO.from_dict(_item) for _item in obj["errors"]] if obj.get("errors") is not None else None,
            "organisationId": obj.get("organisationId"),
            "id": obj.get("id"),
            "entityType": obj.get("entityType"),
            "createdDateTime": obj.get("createdDateTime"),
            "discriminator": obj.get("discriminator"),
            "_etag": obj.get("_etag"),
            "hasErrors": obj.get("hasErrors"),
            "isReadOnly": obj.get("isReadOnly")
        })
        return _obj
