# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from billing_client.models.payment_collection_details_dto import PaymentCollectionDetailsDTO
from billing_client.models.payment_intent_state_dto import PaymentIntentStateDTO
from billing_client.models.payment_method import PaymentMethod
from billing_client.models.payment_process_status import PaymentProcessStatus
from billing_client.models.payment_status_history_dto import PaymentStatusHistoryDTO
from billing_client.models.psp_instrument_snapshot_dto import PspInstrumentSnapshotDTO
from typing import Optional, Set
from typing_extensions import Self

class PaymentDetailsDTO(BaseModel):
    """
    PaymentDetailsDTO
    """ # noqa: E501
    paid: Optional[StrictBool] = None
    current_payment_status: Optional[PaymentProcessStatus] = Field(default=None, alias="currentPaymentStatus")
    payment_reference: Optional[StrictStr] = Field(default=None, alias="paymentReference")
    payment_method: Optional[PaymentMethod] = Field(default=None, alias="paymentMethod")
    collection_details: Optional[PaymentCollectionDetailsDTO] = Field(default=None, alias="collectionDetails")
    direct_debit_collection_date: Optional[datetime] = Field(default=None, alias="directDebitCollectionDate")
    amount_of_times_retried: Optional[StrictInt] = Field(default=None, alias="amountOfTimesRetried")
    status_history: Optional[List[PaymentStatusHistoryDTO]] = Field(default=None, alias="statusHistory")
    payment_intent: Optional[PaymentIntentStateDTO] = Field(default=None, alias="paymentIntent")
    psp_instrument: Optional[PspInstrumentSnapshotDTO] = Field(default=None, alias="pspInstrument")
    __properties: ClassVar[List[str]] = ["paid", "currentPaymentStatus", "paymentReference", "paymentMethod", "collectionDetails", "directDebitCollectionDate", "amountOfTimesRetried", "statusHistory", "paymentIntent", "pspInstrument"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentDetailsDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of collection_details
        if self.collection_details:
            _dict['collectionDetails'] = self.collection_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in status_history (list)
        _items = []
        if self.status_history:
            for _item_status_history in self.status_history:
                if _item_status_history:
                    _items.append(_item_status_history.to_dict())
            _dict['statusHistory'] = _items
        # override the default output from pydantic by calling `to_dict()` of payment_intent
        if self.payment_intent:
            _dict['paymentIntent'] = self.payment_intent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of psp_instrument
        if self.psp_instrument:
            _dict['pspInstrument'] = self.psp_instrument.to_dict()
        # set to None if payment_reference (nullable) is None
        # and model_fields_set contains the field
        if self.payment_reference is None and "payment_reference" in self.model_fields_set:
            _dict['paymentReference'] = None

        # set to None if collection_details (nullable) is None
        # and model_fields_set contains the field
        if self.collection_details is None and "collection_details" in self.model_fields_set:
            _dict['collectionDetails'] = None

        # set to None if status_history (nullable) is None
        # and model_fields_set contains the field
        if self.status_history is None and "status_history" in self.model_fields_set:
            _dict['statusHistory'] = None

        # set to None if payment_intent (nullable) is None
        # and model_fields_set contains the field
        if self.payment_intent is None and "payment_intent" in self.model_fields_set:
            _dict['paymentIntent'] = None

        # set to None if psp_instrument (nullable) is None
        # and model_fields_set contains the field
        if self.psp_instrument is None and "psp_instrument" in self.model_fields_set:
            _dict['pspInstrument'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentDetailsDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paid": obj.get("paid"),
            "currentPaymentStatus": obj.get("currentPaymentStatus"),
            "paymentReference": obj.get("paymentReference"),
            "paymentMethod": obj.get("paymentMethod"),
            "collectionDetails": PaymentCollectionDetailsDTO.from_dict(obj["collectionDetails"]) if obj.get("collectionDetails") is not None else None,
            "directDebitCollectionDate": obj.get("directDebitCollectionDate"),
            "amountOfTimesRetried": obj.get("amountOfTimesRetried"),
            "statusHistory": [PaymentStatusHistoryDTO.from_dict(_item) for _item in obj["statusHistory"]] if obj.get("statusHistory") is not None else None,
            "paymentIntent": PaymentIntentStateDTO.from_dict(obj["paymentIntent"]) if obj.get("paymentIntent") is not None else None,
            "pspInstrument": PspInstrumentSnapshotDTO.from_dict(obj["pspInstrument"]) if obj.get("pspInstrument") is not None else None
        })
        return _obj
