# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentPlanInstallmentStatus(str, Enum):
    """
    Possible values: 'pending', 'readyforcollection', 'due', 'collectioninprogress', 'paid', 'partiallypaid', 'skipped', 'failed', 'overdue'
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    READYFORCOLLECTION = 'readyforcollection'
    DUE = 'due'
    COLLECTIONINPROGRESS = 'collectioninprogress'
    PAID = 'paid'
    PARTIALLYPAID = 'partiallypaid'
    SKIPPED = 'skipped'
    FAILED = 'failed'
    OVERDUE = 'overdue'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentPlanInstallmentStatus from a JSON string"""
        return cls(json.loads(json_str))
