# coding: utf-8

"""
    Billing

    Billing API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from billing_client.models.payment_provider_type import PaymentProviderType
from billing_client.models.psp_refund_ineligibility_reason import PspRefundIneligibilityReason
from typing import Optional, Set
from typing_extensions import Self

class PspRefundEligibilityDTO(BaseModel):
    """
    PspRefundEligibilityDTO
    """ # noqa: E501
    is_refundable: Optional[StrictBool] = Field(default=None, alias="isRefundable")
    reason: Optional[PspRefundIneligibilityReason] = None
    refundable_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="refundableAmount")
    payment_intent_id: Optional[StrictStr] = Field(default=None, alias="paymentIntentId")
    payment_id: Optional[StrictStr] = Field(default=None, alias="paymentId")
    provider: Optional[PaymentProviderType] = None
    provider_workspace_account_id: Optional[StrictStr] = Field(default=None, alias="providerWorkspaceAccountId")
    provider_external_payment_id: Optional[StrictStr] = Field(default=None, alias="providerExternalPaymentId")
    __properties: ClassVar[List[str]] = ["isRefundable", "reason", "refundableAmount", "paymentIntentId", "paymentId", "provider", "providerWorkspaceAccountId", "providerExternalPaymentId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PspRefundEligibilityDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if payment_intent_id (nullable) is None
        # and model_fields_set contains the field
        if self.payment_intent_id is None and "payment_intent_id" in self.model_fields_set:
            _dict['paymentIntentId'] = None

        # set to None if payment_id (nullable) is None
        # and model_fields_set contains the field
        if self.payment_id is None and "payment_id" in self.model_fields_set:
            _dict['paymentId'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if provider_workspace_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_workspace_account_id is None and "provider_workspace_account_id" in self.model_fields_set:
            _dict['providerWorkspaceAccountId'] = None

        # set to None if provider_external_payment_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_external_payment_id is None and "provider_external_payment_id" in self.model_fields_set:
            _dict['providerExternalPaymentId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PspRefundEligibilityDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isRefundable": obj.get("isRefundable"),
            "reason": obj.get("reason"),
            "refundableAmount": obj.get("refundableAmount"),
            "paymentIntentId": obj.get("paymentIntentId"),
            "paymentId": obj.get("paymentId"),
            "provider": obj.get("provider"),
            "providerWorkspaceAccountId": obj.get("providerWorkspaceAccountId"),
            "providerExternalPaymentId": obj.get("providerExternalPaymentId")
        })
        return _obj
