# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from configuration_client.models.bank_holiday_dto import BankHolidayDTO
from configuration_client.models.country_code import CountryCode
from configuration_client.models.entity_subject_type import EntitySubjectType
from typing import Optional, Set
from typing_extensions import Self

class BankHolidayCalendarDTO(BaseModel):
    """
    BankHolidayCalendarDTO
    """ # noqa: E501
    country_code: Optional[CountryCode] = Field(default=None, alias="countryCode")
    bank_holidays: Optional[List[BankHolidayDTO]] = Field(default=None, alias="bankHolidays")
    exclude_by_name: Optional[StrictBool] = Field(default=None, alias="excludeByName")
    excluded_names: Optional[List[StrictStr]] = Field(default=None, alias="excludedNames")
    id: Optional[StrictStr] = None
    entity_type: Optional[EntitySubjectType] = Field(default=None, alias="entityType")
    created_date_time: Optional[datetime] = Field(default=None, alias="createdDateTime")
    discriminator: Optional[StrictStr] = None
    etag: Optional[StrictStr] = Field(default=None, alias="_etag")
    has_errors: Optional[StrictBool] = Field(default=None, alias="hasErrors")
    is_read_only: Optional[StrictBool] = Field(default=None, alias="isReadOnly")
    __properties: ClassVar[List[str]] = ["countryCode", "bankHolidays", "excludeByName", "excludedNames", "id", "entityType", "createdDateTime", "discriminator", "_etag", "hasErrors", "isReadOnly"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankHolidayCalendarDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bank_holidays (list)
        _items = []
        if self.bank_holidays:
            for _item_bank_holidays in self.bank_holidays:
                if _item_bank_holidays:
                    _items.append(_item_bank_holidays.to_dict())
            _dict['bankHolidays'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankHolidayCalendarDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "countryCode": obj.get("countryCode"),
            "bankHolidays": [BankHolidayDTO.from_dict(_item) for _item in obj["bankHolidays"]] if obj.get("bankHolidays") is not None else None,
            "excludeByName": obj.get("excludeByName"),
            "excludedNames": obj.get("excludedNames"),
            "id": obj.get("id"),
            "entityType": obj.get("entityType"),
            "createdDateTime": obj.get("createdDateTime"),
            "discriminator": obj.get("discriminator"),
            "_etag": obj.get("_etag"),
            "hasErrors": obj.get("hasErrors"),
            "isReadOnly": obj.get("isReadOnly")
        })
        return _obj
