# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from configuration_client.models.incrementation_type import IncrementationType
from configuration_client.models.metering_issue_error import MeteringIssueError
from typing import Optional, Set
from typing_extensions import Self

class BaseMeteringValidationRuleDTOUncontractedConsumptionValidationRuleDTO(BaseModel):
    """
    BaseMeteringValidationRuleDTOUncontractedConsumptionValidationRuleDTO
    """ # noqa: E501
    type: Optional[StrictStr] = None
    evaluation_window_days: Optional[StrictInt] = Field(default=None, alias="evaluationWindowDays")
    grace_days_before_supply_start: Optional[StrictInt] = Field(default=None, alias="graceDaysBeforeSupplyStart")
    grace_days_after_supply_end: Optional[StrictInt] = Field(default=None, alias="graceDaysAfterSupplyEnd")
    maximum_allowed_consumption: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maximumAllowedConsumption")
    error: Optional[MeteringIssueError] = None
    enabled: Optional[StrictBool] = None
    synchronous: Optional[StrictBool] = None
    supported_incrementation_types: Optional[List[IncrementationType]] = Field(default=None, alias="supportedIncrementationTypes")
    __properties: ClassVar[List[str]] = ["type", "evaluationWindowDays", "graceDaysBeforeSupplyStart", "graceDaysAfterSupplyEnd", "maximumAllowedConsumption", "error", "enabled", "synchronous", "supportedIncrementationTypes"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BaseMeteringValidationRuleDTO:UncontractedConsumption']):
            raise ValueError("must be one of enum values ('BaseMeteringValidationRuleDTO:UncontractedConsumption')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BaseMeteringValidationRuleDTOUncontractedConsumptionValidationRuleDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BaseMeteringValidationRuleDTOUncontractedConsumptionValidationRuleDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "evaluationWindowDays": obj.get("evaluationWindowDays"),
            "graceDaysBeforeSupplyStart": obj.get("graceDaysBeforeSupplyStart"),
            "graceDaysAfterSupplyEnd": obj.get("graceDaysAfterSupplyEnd"),
            "maximumAllowedConsumption": obj.get("maximumAllowedConsumption"),
            "error": obj.get("error"),
            "enabled": obj.get("enabled"),
            "synchronous": obj.get("synchronous"),
            "supportedIncrementationTypes": obj.get("supportedIncrementationTypes")
        })
        return _obj
