# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from configuration_client.models.billing_calculation_type import BillingCalculationType
from configuration_client.models.unit_of_measure import UnitOfMeasure
from typing import Optional, Set
from typing_extensions import Self

class BillingCalculationTypeParametersDTO(BaseModel):
    """
    BillingCalculationTypeParametersDTO
    """ # noqa: E501
    unit_of_measure: UnitOfMeasure = Field(alias="unitOfMeasure")
    billing_calculation_type: Optional[BillingCalculationType] = Field(default=None, alias="billingCalculationType")
    __properties: ClassVar[List[str]] = ["unitOfMeasure", "billingCalculationType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BillingCalculationTypeParametersDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "billing_calculation_type",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if billing_calculation_type (nullable) is None
        # and model_fields_set contains the field
        if self.billing_calculation_type is None and "billing_calculation_type" in self.model_fields_set:
            _dict['billingCalculationType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BillingCalculationTypeParametersDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unitOfMeasure": obj.get("unitOfMeasure"),
            "billingCalculationType": obj.get("billingCalculationType")
        })
        return _obj


