# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ImportType(str, Enum):
    """
    ImportType
    """

    """
    allowed enum values
    """
    BILLINGTARIFF = 'billingtariff'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ImportType from a JSON string"""
        return cls(json.loads(json_str))


