# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NumberSequenceReferenceEntity(str, Enum):
    """
    NumberSequenceReferenceEntity
    """

    """
    allowed enum values
    """
    CUSTOMER = 'customer'
    CONTRACT = 'contract'
    INVOICE = 'invoice'
    MANDATE = 'mandate'
    EXPORTJOB = 'exportjob'
    COLLECTIONCASE = 'collectioncase'
    BANKINGTRANSACTION = 'bankingtransaction'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NumberSequenceReferenceEntity from a JSON string"""
        return cls(json.loads(json_str))


