# coding: utf-8

"""
    Configuration

    Configuration API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from configuration_client.models.communication_type import CommunicationType
from configuration_client.models.entity_subject_type import EntitySubjectType
from configuration_client.models.entity_type_dto import EntityTypeDTO
from configuration_client.models.reminder_email_template_dto import ReminderEmailTemplateDTO
from configuration_client.models.reminder_pdf_template_dto import ReminderPdfTemplateDTO
from configuration_client.models.scenario_grouping_type import ScenarioGroupingType
from configuration_client.models.template_object_type import TemplateObjectType
from typing import Optional, Set
from typing_extensions import Self

class ReminderScenarioDTO(BaseModel):
    """
    ReminderScenarioDTO
    """ # noqa: E501
    default_communication_type: Optional[CommunicationType] = Field(default=None, alias="defaultCommunicationType")
    translation_list_id: Optional[StrictStr] = Field(default=None, alias="translationListId")
    translation_list_history_id: Optional[StrictStr] = Field(default=None, alias="translationListHistoryId")
    data_type: Optional[TemplateObjectType] = Field(default=None, alias="dataType")
    entity_subject_type: Optional[EntitySubjectType] = Field(default=None, alias="entitySubjectType")
    entity_subject_sub_type: Optional[StrictStr] = Field(default=None, alias="entitySubjectSubType")
    grouping_type: Optional[ScenarioGroupingType] = Field(default=None, alias="groupingType")
    entity_type: Optional[EntityTypeDTO] = Field(default=None, alias="entityType")
    available_communication_types: Optional[List[CommunicationType]] = Field(default=None, alias="availableCommunicationTypes")
    pdf_template: Optional[ReminderPdfTemplateDTO] = Field(default=None, alias="pdfTemplate")
    email_template: Optional[ReminderEmailTemplateDTO] = Field(default=None, alias="emailTemplate")
    __properties: ClassVar[List[str]] = ["defaultCommunicationType", "translationListId", "translationListHistoryId", "dataType", "entitySubjectType", "entitySubjectSubType", "groupingType", "entityType", "availableCommunicationTypes", "pdfTemplate", "emailTemplate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReminderScenarioDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of entity_type
        if self.entity_type:
            _dict['entityType'] = self.entity_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pdf_template
        if self.pdf_template:
            _dict['pdfTemplate'] = self.pdf_template.to_dict()
        # override the default output from pydantic by calling `to_dict()` of email_template
        if self.email_template:
            _dict['emailTemplate'] = self.email_template.to_dict()
        # set to None if default_communication_type (nullable) is None
        # and model_fields_set contains the field
        if self.default_communication_type is None and "default_communication_type" in self.model_fields_set:
            _dict['defaultCommunicationType'] = None

        # set to None if translation_list_id (nullable) is None
        # and model_fields_set contains the field
        if self.translation_list_id is None and "translation_list_id" in self.model_fields_set:
            _dict['translationListId'] = None

        # set to None if translation_list_history_id (nullable) is None
        # and model_fields_set contains the field
        if self.translation_list_history_id is None and "translation_list_history_id" in self.model_fields_set:
            _dict['translationListHistoryId'] = None

        # set to None if data_type (nullable) is None
        # and model_fields_set contains the field
        if self.data_type is None and "data_type" in self.model_fields_set:
            _dict['dataType'] = None

        # set to None if entity_subject_type (nullable) is None
        # and model_fields_set contains the field
        if self.entity_subject_type is None and "entity_subject_type" in self.model_fields_set:
            _dict['entitySubjectType'] = None

        # set to None if entity_subject_sub_type (nullable) is None
        # and model_fields_set contains the field
        if self.entity_subject_sub_type is None and "entity_subject_sub_type" in self.model_fields_set:
            _dict['entitySubjectSubType'] = None

        # set to None if grouping_type (nullable) is None
        # and model_fields_set contains the field
        if self.grouping_type is None and "grouping_type" in self.model_fields_set:
            _dict['groupingType'] = None

        # set to None if entity_type (nullable) is None
        # and model_fields_set contains the field
        if self.entity_type is None and "entity_type" in self.model_fields_set:
            _dict['entityType'] = None

        # set to None if available_communication_types (nullable) is None
        # and model_fields_set contains the field
        if self.available_communication_types is None and "available_communication_types" in self.model_fields_set:
            _dict['availableCommunicationTypes'] = None

        # set to None if pdf_template (nullable) is None
        # and model_fields_set contains the field
        if self.pdf_template is None and "pdf_template" in self.model_fields_set:
            _dict['pdfTemplate'] = None

        # set to None if email_template (nullable) is None
        # and model_fields_set contains the field
        if self.email_template is None and "email_template" in self.model_fields_set:
            _dict['emailTemplate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReminderScenarioDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaultCommunicationType": obj.get("defaultCommunicationType"),
            "translationListId": obj.get("translationListId"),
            "translationListHistoryId": obj.get("translationListHistoryId"),
            "dataType": obj.get("dataType"),
            "entitySubjectType": obj.get("entitySubjectType"),
            "entitySubjectSubType": obj.get("entitySubjectSubType"),
            "groupingType": obj.get("groupingType"),
            "entityType": EntityTypeDTO.from_dict(obj["entityType"]) if obj.get("entityType") is not None else None,
            "availableCommunicationTypes": obj.get("availableCommunicationTypes"),
            "pdfTemplate": ReminderPdfTemplateDTO.from_dict(obj["pdfTemplate"]) if obj.get("pdfTemplate") is not None else None,
            "emailTemplate": ReminderEmailTemplateDTO.from_dict(obj["emailTemplate"]) if obj.get("emailTemplate") is not None else None
        })
        return _obj


