# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from masterdata_client.models.annual_statement_status import AnnualStatementStatus
from typing import Optional, Set
from typing_extensions import Self

class AnnualStatementReference(BaseModel):
    """
    AnnualStatementReference
    """ # noqa: E501
    annual_statement_id: Optional[StrictStr] = Field(default=None, alias="annualStatementId")
    annual_statement_number: Optional[StrictStr] = Field(default=None, alias="annualStatementNumber")
    year: Optional[StrictInt] = None
    version: Optional[StrictInt] = None
    status: Optional[AnnualStatementStatus] = None
    __properties: ClassVar[List[str]] = ["annualStatementId", "annualStatementNumber", "year", "version", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnnualStatementReference from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if annual_statement_id (nullable) is None
        # and model_fields_set contains the field
        if self.annual_statement_id is None and "annual_statement_id" in self.model_fields_set:
            _dict['annualStatementId'] = None

        # set to None if annual_statement_number (nullable) is None
        # and model_fields_set contains the field
        if self.annual_statement_number is None and "annual_statement_number" in self.model_fields_set:
            _dict['annualStatementNumber'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnnualStatementReference from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "annualStatementId": obj.get("annualStatementId"),
            "annualStatementNumber": obj.get("annualStatementNumber"),
            "year": obj.get("year"),
            "version": obj.get("version"),
            "status": obj.get("status")
        })
        return _obj


