# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MeasurementSource(str, Enum):
    """
    MeasurementSource
    """

    """
    allowed enum values
    """
    IMPORTJOB = 'importjob'
    MOVEREQUEST = 'moverequest'
    MEASUREMENTIMPORT = 'measurementimport'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MeasurementSource from a JSON string"""
        return cls(json.loads(json_str))


