# coding: utf-8

"""
    Masterdata

    MasterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from masterdata_client.models.meter_dto import MeterDTO
from masterdata_client.models.utility_type import UtilityType
from typing import Optional, Set
from typing_extensions import Self

class PrepaymentMeterInstalledDTO(BaseModel):
    """
    PrepaymentMeterInstalledDTO
    """ # noqa: E501
    meter: Optional[MeterDTO] = None
    utility_types_on_start_date: Optional[List[UtilityType]] = Field(default=None, alias="utilityTypesOnStartDate")
    __properties: ClassVar[List[str]] = ["meter", "utilityTypesOnStartDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrepaymentMeterInstalledDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meter
        if self.meter:
            _dict['meter'] = self.meter.to_dict()
        # set to None if meter (nullable) is None
        # and model_fields_set contains the field
        if self.meter is None and "meter" in self.model_fields_set:
            _dict['meter'] = None

        # set to None if utility_types_on_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.utility_types_on_start_date is None and "utility_types_on_start_date" in self.model_fields_set:
            _dict['utilityTypesOnStartDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrepaymentMeterInstalledDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "meter": MeterDTO.from_dict(obj["meter"]) if obj.get("meter") is not None else None,
            "utilityTypesOnStartDate": obj.get("utilityTypesOnStartDate")
        })
        return _obj


