# coding: utf-8

"""
    Communication

    Communication API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AdvanceAmountChangedBy(str, Enum):
    """
    AdvanceAmountChangedBy
    """

    """
    allowed enum values
    """
    SYSTEMINVOICECALCULATION = 'systeminvoicecalculation'
    CUSTOMER = 'customer'
    CUSTOMERSERVICEREPRESENTATIVE = 'customerservicerepresentative'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdvanceAmountChangedBy from a JSON string"""
        return cls(json.loads(json_str))


