# coding: utf-8

"""
    Communication

    Communication API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SubjectReferenceParametersDTOCustomerSubjectReferenceParametersDTO(BaseModel):
    """
    SubjectReferenceParametersDTOCustomerSubjectReferenceParametersDTO
    """ # noqa: E501
    type: Optional[StrictStr] = None
    customer_account_number: Optional[StrictStr] = Field(default=None, alias="customerAccountNumber")
    customer_display_name: Optional[StrictStr] = Field(default=None, alias="customerDisplayName")
    __properties: ClassVar[List[str]] = ["type", "customerAccountNumber", "customerDisplayName"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Customer']):
            raise ValueError("must be one of enum values ('Customer')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubjectReferenceParametersDTOCustomerSubjectReferenceParametersDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if customer_account_number (nullable) is None
        # and model_fields_set contains the field
        if self.customer_account_number is None and "customer_account_number" in self.model_fields_set:
            _dict['customerAccountNumber'] = None

        # set to None if customer_display_name (nullable) is None
        # and model_fields_set contains the field
        if self.customer_display_name is None and "customer_display_name" in self.model_fields_set:
            _dict['customerDisplayName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubjectReferenceParametersDTOCustomerSubjectReferenceParametersDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "customerAccountNumber": obj.get("customerAccountNumber"),
            "customerDisplayName": obj.get("customerDisplayName")
        })
        return _obj
