# coding: utf-8

"""
    RegionalRegulations

    Regional Regulations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from regionalregulations_client.models.ssh_authentication_method import SshAuthenticationMethod

class TestSshAuthenticationMethod(unittest.TestCase):
    """SshAuthenticationMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSshAuthenticationMethod(self):
        """Test SshAuthenticationMethod"""
        # inst = SshAuthenticationMethod()

if __name__ == '__main__':
    unittest.main()
