# coding: utf-8

"""
    RegionalRegulations

    Regional Regulations API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from regionalregulations_client.models.meter_quick_filter import MeterQuickFilter

class TestMeterQuickFilter(unittest.TestCase):
    """MeterQuickFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeterQuickFilter(self):
        """Test MeterQuickFilter"""
        # inst = MeterQuickFilter()

if __name__ == '__main__':
    unittest.main()
