# coding: utf-8

"""
    Forecasting

    Forecasting API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecasting_client.models.import_status import ImportStatus

class TestImportStatus(unittest.TestCase):
    """ImportStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportStatus(self):
        """Test ImportStatus"""
        # inst = ImportStatus()

if __name__ == '__main__':
    unittest.main()
