# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachments_client.models.bulk_delete_entity_attachment_group_request import BulkDeleteEntityAttachmentGroupRequest

class TestBulkDeleteEntityAttachmentGroupRequest(unittest.TestCase):
    """BulkDeleteEntityAttachmentGroupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkDeleteEntityAttachmentGroupRequest:
        """Test BulkDeleteEntityAttachmentGroupRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkDeleteEntityAttachmentGroupRequest`
        """
        model = BulkDeleteEntityAttachmentGroupRequest()
        if include_optional:
            return BulkDeleteEntityAttachmentGroupRequest(
                only_validate = True,
                var_query_params = attachments_client.models.get_entity_attachment_group_query_params.GetEntityAttachmentGroupQueryParams(
                    flex_search = '', 
                    include_only_ids = [
                        ''
                        ], 
                    exclude_ids = [
                        ''
                        ], 
                    subject_type = '', 
                    subject_id = '', 
                    viewed = True, 
                    visibilities = [
                        ''
                        ], 
                    created_start_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_end_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    validity_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                quick_filter = ''
            )
        else:
            return BulkDeleteEntityAttachmentGroupRequest(
        )
        """

    def testBulkDeleteEntityAttachmentGroupRequest(self):
        """Test BulkDeleteEntityAttachmentGroupRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
