# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachments_client.models.metering_issue_error import MeteringIssueError

class TestMeteringIssueError(unittest.TestCase):
    """MeteringIssueError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeteringIssueError(self):
        """Test MeteringIssueError"""
        # inst = MeteringIssueError()

if __name__ == '__main__':
    unittest.main()
