# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachments_client.models.update_entity_attachment_visibility_request import UpdateEntityAttachmentVisibilityRequest

class TestUpdateEntityAttachmentVisibilityRequest(unittest.TestCase):
    """UpdateEntityAttachmentVisibilityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateEntityAttachmentVisibilityRequest:
        """Test UpdateEntityAttachmentVisibilityRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateEntityAttachmentVisibilityRequest`
        """
        model = UpdateEntityAttachmentVisibilityRequest()
        if include_optional:
            return UpdateEntityAttachmentVisibilityRequest(
                customer_id = '',
                visibility = 'internal'
            )
        else:
            return UpdateEntityAttachmentVisibilityRequest(
        )
        """

    def testUpdateEntityAttachmentVisibilityRequest(self):
        """Test UpdateEntityAttachmentVisibilityRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
