# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachments_client.models.organization_parameters_data_object import OrganizationParametersDataObject

class TestOrganizationParametersDataObject(unittest.TestCase):
    """OrganizationParametersDataObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationParametersDataObject:
        """Test OrganizationParametersDataObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationParametersDataObject`
        """
        model = OrganizationParametersDataObject()
        if include_optional:
            return OrganizationParametersDataObject(
                billing_parameters = attachments_client.models.billing_parameters_data_object.BillingParametersDataObject(
                    skip_approval = True, 
                    skip_payment = True, 
                    enable_invoice_collection = True, )
            )
        else:
            return OrganizationParametersDataObject(
        )
        """

    def testOrganizationParametersDataObject(self):
        """Test OrganizationParametersDataObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
