# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachments_client.models.portal_notification_type import PortalNotificationType

class TestPortalNotificationType(unittest.TestCase):
    """PortalNotificationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortalNotificationType(self):
        """Test PortalNotificationType"""
        # inst = PortalNotificationType()

if __name__ == '__main__':
    unittest.main()
