# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachments_client.models.template_data_object import TemplateDataObject

class TestTemplateDataObject(unittest.TestCase):
    """TemplateDataObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateDataObject:
        """Test TemplateDataObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateDataObject`
        """
        model = TemplateDataObject()
        if include_optional:
            return TemplateDataObject(
                created_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                etag = '',
                discriminator = '',
                entity_type = 'none',
                ttl = 0.0,
                cid = '',
                ts = 56,
                user_id = '',
                require_attention = True,
                has_errors = True,
                has_warnings = True,
                organisation_id = '',
                organization = attachments_client.models.organization_data_object.OrganizationDataObject(
                    primary_color = '', 
                    secondary_color = '', 
                    bank_account = '', 
                    bank_account_holder = '', 
                    vat_account_number = '', 
                    company_account_number = '', 
                    description = '', 
                    logo = '', 
                    logo_cdn_url = '', 
                    address = null, 
                    email_address = '', 
                    telephone = '', 
                    website = '', 
                    telephone_interruptions = '', 
                    support = '', 
                    customer_portal = '', 
                    parameters = null, ),
                culture = ,
                decimal_and_currency_culture = ,
                validation_errors = [
                    attachments_client.models.template_validation_error_details.TemplateValidationErrorDetails(
                        originator_type = null, 
                        originator_id = '', 
                        message = null, 
                        subject_type = null, 
                        subject_id = '', )
                    ]
            )
        else:
            return TemplateDataObject(
        )
        """

    def testTemplateDataObject(self):
        """Test TemplateDataObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
