# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachments_client.models.update_payment_link_request import UpdatePaymentLinkRequest

class TestUpdatePaymentLinkRequest(unittest.TestCase):
    """UpdatePaymentLinkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdatePaymentLinkRequest:
        """Test UpdatePaymentLinkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdatePaymentLinkRequest`
        """
        model = UpdatePaymentLinkRequest()
        if include_optional:
            return UpdatePaymentLinkRequest(
                payment_link = ''
            )
        else:
            return UpdatePaymentLinkRequest(
        )
        """

    def testUpdatePaymentLinkRequest(self):
        """Test UpdatePaymentLinkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
