# coding: utf-8

"""
    Attachments

    Attachments API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachments_client.models.entity_attachment_group_dto_paged_response_model_dto_api_response_dto import EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO

class TestEntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO(unittest.TestCase):
    """EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO:
        """Test EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO`
        """
        model = EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO()
        if include_optional:
            return EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO(
                errors = [
                    attachments_client.models.localised_error_dto.LocalisedErrorDTO(
                        key = null, 
                        correlation_id = '', 
                        message = '', 
                        message_values = [
                            attachments_client.models.localised_error_dto_message_value.LocalisedErrorDTOMessageValue(
                                data_type = null, 
                                value = '', 
                                capitalize = True, )
                            ], )
                    ],
                success = True,
                applicable_entities_count = 56,
                requested_entities_count = 56,
                succeeded_entities_count = 56,
                is_synchronous = True,
                data = attachments_client.models.entity_attachment_group_dto_paged_response_model_dto.EntityAttachmentGroupDTOPagedResponseModelDTO(
                    results = [
                        attachments_client.models.entity_attachment_group_dto.EntityAttachmentGroupDTO(
                            id = '', 
                            entity_type = null, 
                            created_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            discriminator = '', 
                            _etag = '', 
                            require_attention = True, 
                            has_errors = True, 
                            has_warnings = True, 
                            is_read_only = True, 
                            organisation_id = '', 
                            entity_subject_type = null, 
                            entity_subject_id = '', 
                            entity_subject_display_name = '', 
                            localised_attachment_files = [
                                attachments_client.models.entity_attachment_file_dto.EntityAttachmentFileDTO(
                                    file_name = '', 
                                    localised_file_name = '', 
                                    culture = null, )
                                ], 
                            include_in_welcome_email = True, 
                            visibility = null, 
                            approval_required = True, 
                            validity = null, )
                        ], 
                    has_next_page = True, 
                    next_page_token = '', 
                    total_records = 56, 
                    sortable_fields = [
                        ''
                        ], 
                    aggregate_details = [
                        attachments_client.models.aggregate_details_dto.AggregateDetailsDTO(
                            code = '', 
                            translation = '', 
                            value = 1.337, 
                            value_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], )
            )
        else:
            return EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO(
        )
        """

    def testEntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO(self):
        """Test EntityAttachmentGroupDTOPagedResponseModelDTOApiResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
