# coding: utf-8

"""
    Metering

    MeterData API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from metering_client.models.get_meters_query_params import GetMetersQueryParams
from metering_client.models.metering_issue_error import MeteringIssueError
from metering_client.models.muting_rule_time_period import MutingRuleTimePeriod
from typing import Optional, Set
from typing_extensions import Self

class BulkCreateMutingRuleRequest(BaseModel):
    """
    BulkCreateMutingRuleRequest
    """ # noqa: E501
    error_type: Optional[MeteringIssueError] = Field(default=None, alias="errorType")
    message: Optional[StrictStr] = None
    time_period: Optional[MutingRuleTimePeriod] = Field(default=None, alias="timePeriod")
    only_validate: Optional[StrictBool] = Field(default=None, alias="onlyValidate")
    var_query_params: Optional[GetMetersQueryParams] = Field(default=None, alias="queryParams")
    quick_filter: Optional[StrictStr] = Field(default=None, alias="quickFilter")
    __properties: ClassVar[List[str]] = ["errorType", "message", "timePeriod", "onlyValidate", "queryParams", "quickFilter"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BulkCreateMutingRuleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_query_params
        if self.var_query_params:
            _dict['queryParams'] = self.var_query_params.to_dict()
        # set to None if error_type (nullable) is None
        # and model_fields_set contains the field
        if self.error_type is None and "error_type" in self.model_fields_set:
            _dict['errorType'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if time_period (nullable) is None
        # and model_fields_set contains the field
        if self.time_period is None and "time_period" in self.model_fields_set:
            _dict['timePeriod'] = None

        # set to None if var_query_params (nullable) is None
        # and model_fields_set contains the field
        if self.var_query_params is None and "var_query_params" in self.model_fields_set:
            _dict['queryParams'] = None

        # set to None if quick_filter (nullable) is None
        # and model_fields_set contains the field
        if self.quick_filter is None and "quick_filter" in self.model_fields_set:
            _dict['quickFilter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BulkCreateMutingRuleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "errorType": obj.get("errorType"),
            "message": obj.get("message"),
            "timePeriod": obj.get("timePeriod"),
            "onlyValidate": obj.get("onlyValidate"),
            "queryParams": GetMetersQueryParams.from_dict(obj["queryParams"]) if obj.get("queryParams") is not None else None,
            "quickFilter": obj.get("quickFilter")
        })
        return _obj


